// Expense advances — pure types and helpers.
//
// An advance is money paid to an employee *before* the expense (imprest / salary
// advance). It is the mirror image of an expense claim: HR issues it, then
// recovers it from payroll or at full-and-final settlement. Nothing in this file
// touches Supabase — the panel components own the I/O, the rules that decide what
// an advance means live here so they can be unit-tested without a database.
//
// Money convention: amounts arrive as numeric(14,2) from Postgres, which the
// supabase client hands back as a number-or-string. Every helper coerces with
// Number() before arithmetic so a string amount cannot silently concatenate.
//
// The `outstanding` column is GENERATED in Postgres (amount - recovered_amount,
// floored at 0). `outstandingOf` prefers that value but derives it as a fallback
// so a hand-built row (or a future view that drops the column) still behaves.

export type AdvanceStatus = "open" | "recovered" | "cancelled";

/** Every status the DB CHECK constraint allows, in lifecycle order. */
export const ADVANCE_STATUSES: readonly AdvanceStatus[] = [
  "open",
  "recovered",
  "cancelled",
] as const;

export interface AdvanceRow {
  id: string;
  employee_profile_id: string;
  amount: number | string;
  recovered_amount: number | string;
  /** Generated by Postgres: GREATEST(amount - recovered_amount, 0). */
  outstanding: number | string;
  issued_on: string;
  purpose: string | null;
  status: AdvanceStatus;
  payroll_cycle_id: string | null;
  settled_at: string | null;
  notes: string | null;
  employee_name: string | null;
  employee_number: string | null;
}

export interface AdvanceSummary {
  /** How many advances are still `open` (a count, not money). */
  open: number;
  /** Rupees still to recover across open advances. */
  outstanding: number;
  /** Rupees recovered across every advance. */
  recovered: number;
  /** Rupees issued across every advance. */
  total: number;
}

const STATUS_CLASS: Record<AdvanceStatus, string> = {
  open: "bg-pastel-yellow text-foreground/80 border-0 text-[10px]",
  recovered: "bg-pastel-green text-foreground/80 border-0 text-[10px]",
  cancelled: "bg-muted text-muted-foreground border-0 text-[10px]",
};

/**
 * Tailwind classes for a status pill. Pastel tokens only — the app reads them as
 * a family, so a status never invents its own colour.
 */
export function advanceStatusBadge(status: AdvanceStatus | string): string {
  return STATUS_CLASS[status as AdvanceStatus] ?? STATUS_CLASS.cancelled;
}

const INR = new Intl.NumberFormat("en-IN", { maximumFractionDigits: 2 });

/** Indian-grouped rupees, e.g. 1234567.5 → "12,34,567.5". */
export function formatInr(n: number | string | null | undefined): string {
  const value = Number(n);
  if (!Number.isFinite(value)) return "0";
  return INR.format(value);
}

/**
 * Money still owed on an advance. Prefers the database's generated `outstanding`
 * and falls back to `amount - recovered_amount` when that column is absent or
 * unparseable. Always floored at 0 — over-recovery is impossible in the DB, but
 * a bad seed shouldn't render a negative number.
 */
export function outstandingOf(
  a: Pick<AdvanceRow, "amount" | "recovered_amount"> & { outstanding?: number | string | null },
): number {
  const explicit = a?.outstanding;
  if (explicit !== null && explicit !== undefined && Number.isFinite(Number(explicit))) {
    return Math.max(Number(explicit), 0);
  }
  const derived = Number(a?.amount ?? 0) - Number(a?.recovered_amount ?? 0);
  return Number.isFinite(derived) ? Math.max(derived, 0) : 0;
}

/**
 * Is the advance fully repaid? True when nothing is left outstanding — which is
 * exactly what the DB means by `status = 'recovered'`. A cancelled advance still
 * carries its outstanding balance, so it reads as not recovered.
 */
export function isFullyRecovered(
  a: Pick<AdvanceRow, "amount" | "recovered_amount"> & { outstanding?: number | string | null },
): boolean {
  return outstandingOf(a) <= 0;
}

/**
 * Money totals for the HR summary cards, plus a count of open advances. `open`
 * is a count; the three rupee figures are summed across every row (recovered /
 * total) or the open balance only (outstanding).
 */
export function summarizeAdvances(
  rows: ReadonlyArray<Pick<AdvanceRow, "status" | "amount" | "recovered_amount"> & { outstanding?: number | string | null }>,
): AdvanceSummary {
  return rows.reduce<AdvanceSummary>(
    (acc, r) => {
      acc.total += numberOrZero(r.amount);
      acc.recovered += numberOrZero(r.recovered_amount);
      if (r.status === "open") {
        acc.open += 1;
        acc.outstanding += outstandingOf(r);
      }
      return acc;
    },
    { open: 0, outstanding: 0, recovered: 0, total: 0 },
  );
}

function numberOrZero(n: number | string | null | undefined): number {
  const value = Number(n);
  return Number.isFinite(value) ? value : 0;
}
