// Comp-off (compensatory off) — pure types and helpers.
//
// A comp-off credit is time worked beyond the norm, banked and later taken back
// as leave. Credits are approved by HR, expire after a configurable window, and
// are consumed FIFO when an approved COFF leave request is recorded. Nothing in
// this file touches Supabase — the panel components own the I/O; the rules that
// decide what a credit means live here so they can be unit-tested without a
// database.
//
// Numeric convention: `days`, `used_days` and the generated `remaining` arrive as
// numeric(6,2), which the supabase client hands back as a number-or-string. Every
// helper coerces with Number() before arithmetic, and rounds back to 2 decimals
// so floating addition never leaks 0.30000000000000004 into the UI.

export type CompOffStatus = "pending" | "approved" | "rejected" | "used" | "expired";
export type CompOffSource = "overtime" | "holiday_work" | "weekend" | "manual";

/** Every status the DB CHECK constraint allows, in lifecycle order. */
export const COMP_OFF_STATUSES: readonly CompOffStatus[] = [
  "pending",
  "approved",
  "used",
  "rejected",
  "expired",
] as const;

/** Every source the DB CHECK constraint allows. */
export const COMP_OFF_SOURCES: readonly CompOffSource[] = [
  "overtime",
  "holiday_work",
  "weekend",
  "manual",
] as const;

/** The statuses the HR filter bar offers. */
export const COMP_OFF_FILTERS = [
  "all",
  "pending",
  "approved",
  "used",
  "rejected",
  "expired",
] as const;
export type CompOffFilter = (typeof COMP_OFF_FILTERS)[number];

export interface CompOffCredit {
  id: string;
  employee_profile_id: string;
  earned_on: string;
  days: number | string;
  used_days: number | string;
  /** Generated by Postgres: GREATEST(days - used_days, 0). */
  remaining: number | string;
  reason: string | null;
  source: CompOffSource | string;
  status: CompOffStatus | string;
  approved_at: string | null;
  expires_on: string | null;
}

export interface CompOffSummary {
  /** Every credit, regardless of status. */
  total: number;
  /** Credit counts by status. */
  pending: number;
  approved: number;
  rejected: number;
  used: number;
  expired: number;
  /** Days still spendable: `remaining` across approved, unexpired credits. */
  availableDays: number;
  /** Days already drawn down, across every status. */
  usedDays: number;
}

const STATUS_CLASS: Record<CompOffStatus, string> = {
  pending: "bg-pastel-yellow text-foreground/80 border-0 text-[10px]",
  approved: "bg-pastel-green text-foreground/80 border-0 text-[10px]",
  rejected: "bg-pastel-red text-foreground/80 border-0 text-[10px]",
  used: "bg-pastel-blue text-foreground/80 border-0 text-[10px]",
  expired: "bg-muted text-muted-foreground border-0 text-[10px]",
};

const SOURCE_LABEL: Record<CompOffSource, string> = {
  overtime: "Overtime",
  holiday_work: "Holiday work",
  weekend: "Weekend",
  manual: "Granted",
};

/**
 * Tailwind classes for a status pill. Pastel tokens only — the app reads them as
 * a family, so a status never invents its own colour.
 */
export function compOffStatusBadge(status: CompOffStatus | string): string {
  return STATUS_CLASS[status as CompOffStatus] ?? STATUS_CLASS.expired;
}

/** Human label ("used" → "Used", "holiday_work" → "Holiday work"). */
export function compOffStatusLabel(status: string): string {
  if (!status) return "";
  return status.charAt(0).toUpperCase() + status.slice(1);
}

/** Human label for the credit's origin, with a safe fallback for unknown sources. */
export function compOffSourceLabel(source: string): string {
  return SOURCE_LABEL[source as CompOffSource] ?? "Granted";
}

/** Day counts render as trim-decimals: 2 → "2", 1.5 → "1.5", null → "0". */
export function formatDays(n: number | string | null | undefined): string {
  const value = Number(n);
  if (!Number.isFinite(value)) return "0";
  return String(round2(value));
}

/**
 * Days still spendable, mirroring the DB's `my_comp_off().available_days`: sum of
 * `remaining` across approved credits that have not yet expired. `asOf` is an ISO
 * date so expiry can be pinned in tests; it defaults to today.
 */
export function availableOf(
  credits: ReadonlyArray<Pick<CompOffCredit, "status" | "remaining" | "expires_on">>,
  asOf: string = todayIso(),
): number {
  return round2(
    credits.reduce((acc, c) => {
      if (c.status !== "approved") return acc;
      if (c.expires_on && c.expires_on < asOf) return acc;
      return acc + numberOrZero(c.remaining);
    }, 0),
  );
}

/**
 * Counts by status plus the two day totals, for the HR summary cards. `total`,
 * `pending`, `approved`, `rejected`, `used` and `expired` are row counts;
 * `availableDays` and `usedDays` are day sums.
 */
export function summarizeCompOff(
  credits: ReadonlyArray<Pick<CompOffCredit, "status" | "days" | "used_days" | "remaining" | "expires_on">>,
  asOf: string = todayIso(),
): CompOffSummary {
  const count = (status: CompOffStatus) => credits.filter((c) => c.status === status).length;
  return {
    total: credits.length,
    pending: count("pending"),
    approved: count("approved"),
    rejected: count("rejected"),
    used: count("used"),
    expired: count("expired"),
    availableDays: availableOf(credits, asOf),
    usedDays: round2(credits.reduce((acc, c) => acc + numberOrZero(c.used_days), 0)),
  };
}

function round2(n: number): number {
  return Math.round(n * 100) / 100;
}

function numberOrZero(n: number | string | null | undefined): number {
  const value = Number(n);
  return Number.isFinite(value) ? value : 0;
}

function todayIso(): string {
  return new Date().toISOString().slice(0, 10);
}
