project_id = "sctttxxgtsoeodulosdg"

[functions.invite-user]
verify_jwt = false

[functions.bulk-invite-users]
verify_jwt = false

[functions.whatsapp-otp]
verify_jwt = false

[functions.ai-first-call]
verify_jwt = false

[functions.lead-ingest]
verify_jwt = false