/**
 * Predefined boards (Class 10/12) and universities for searchable dropdowns.
 * When a user picks "Other" / types a custom entry, the application gets flagged
 * with "custom_board" or "custom_university" so admins can verify before issuing offers.
 */

export const BOARDS_LIST = [
  'CBSE',
  'ICSE / ISC',
  'UP Board (UPMSP)',
  'Bihar Board (BSEB)',
  'Rajasthan Board (RBSE)',
  'MP Board (MPBSE)',
  'Maharashtra Board (MSBSHSE)',
  'Gujarat Board (GSEB)',
  'West Bengal Board (WBBSE/WBCHSE)',
  'Tamil Nadu Board (TN-SSLC/HSC)',
  'Karnataka Board (KSEEB)',
  'Andhra Pradesh Board (BSEAP/BIEAP)',
  'Telangana Board (BSE-TS/BIE-TS)',
  'Kerala Board (KBPE/DHSE)',
  'Punjab Board (PSEB)',
  'Haryana Board (BSEH)',
  'Uttarakhand Board (UBSE)',
  'Jharkhand Board (JAC)',
  'Chhattisgarh Board (CGBSE)',
  'Odisha Board (BSE/CHSE)',
  'Assam Board (SEBA/AHSEC)',
  'Himachal Pradesh Board (HPBOSE)',
  'Jammu & Kashmir Board (JKBOSE)',
  'Goa Board (GBSHSE)',
  'Nagaland Board (NBSE)',
  'Meghalaya Board (MBOSE)',
  'Manipur Board (BSEM/COHSEM)',
  'Mizoram Board (MBSE)',
  'Tripura Board (TBSE)',
  'Arunachal Pradesh Board',
  'Sikkim Board',
  'NIOS (National Institute of Open Schooling)',
  'IB (International Baccalaureate)',
  'Cambridge (IGCSE / A-Levels)',
  'CISCE',
];

export const UNIVERSITIES_LIST = [
  'University of Delhi',
  'Jawaharlal Nehru University (JNU)',
  'Banaras Hindu University (BHU)',
  'Aligarh Muslim University (AMU)',
  'University of Allahabad',
  'University of Lucknow',
  'Chaudhary Charan Singh University (CCSU)',
  'Dr. A.P.J. Abdul Kalam Technical University (AKTU)',
  'Mahatma Jyotiba Phule Rohilkhand University (MJPRU)',
  'Guru Gobind Singh Indraprastha University (GGSIPU)',
  'Maharshi Dayanand University (MDU), Rohtak',
  'Kurukshetra University',
  'Chaudhary Devi Lal University (CDLU)',
  'Panjab University, Chandigarh',
  'University of Rajasthan',
  'Maharaja Ganga Singh University (MGSU)',
  'Jai Narain Vyas University, Jodhpur',
  'Rajasthan Technical University (RTU)',
  'Gujarat University',
  'Gujarat Technological University (GTU)',
  'Savitribai Phule Pune University (SPPU)',
  'University of Mumbai',
  'Shivaji University, Kolhapur',
  'Osmania University, Hyderabad',
  'Anna University, Chennai',
  'University of Madras',
  'Bangalore University',
  'Visvesvaraya Technological University (VTU)',
  'University of Calcutta',
  'Jadavpur University',
  'Utkal University, Bhubaneswar',
  'Patna University',
  'Ranchi University',
  'Barkatullah University, Bhopal',
  'Devi Ahilya Vishwavidyalaya (DAVV), Indore',
  'Hemwati Nandan Bahuguna Garhwal University',
  'Kumaun University',
  'University of Jammu',
  'University of Kashmir',
  'Gauhati University',
  'Dibrugarh University',
  'North-Eastern Hill University (NEHU)',
  'Manipur University',
  'Tripura University',
  'IGNOU (Indira Gandhi National Open University)',
  'Lovely Professional University (LPU)',
  'Amity University',
  'Sharda University',
  'Galgotias University',
  'SRM Institute of Science and Technology',
  'VIT University (Vellore)',
  'Manipal Academy of Higher Education',
  'Symbiosis International University',
  'Christ University, Bangalore',
  'Jamia Millia Islamia',
  'NIMT University',
];

/** Check if a value is from the predefined list */
export function isPredefinedBoard(value: string): boolean {
  return BOARDS_LIST.some(b => b.toLowerCase() === value.toLowerCase());
}

export function isPredefinedUniversity(value: string): boolean {
  return UNIVERSITIES_LIST.some(u => u.toLowerCase() === value.toLowerCase());
}
