/**
 * Predefined boards (Class 10/12) and universities for searchable dropdowns.
 * Universities sourced from official UGC list.
 * When a user picks "Other" / types a custom entry, the application gets flagged
 * with "custom_board" or "custom_university" so admins can verify before issuing offers.
 */

export const BOARDS_LIST = [
  'Central Board of Secondary Education (CBSE), Delhi',
  'Council for Indian School Certificate Examinations (CISCE), New Delhi',
  'National Institute of Open Schooling, New Delhi',
  'Andhra Pradesh Board of Intermediate Education, Vijayawada',
  'Andhra Pradesh Board of Secondary Education, Vijayawada',
  'Andhra Pradesh Open School Society',
  'Assam Higher Secondary Education Council, Guwahati',
  'Assam Board of Secondary Education, Guwahati',
  'Assam State Open School, Guwahati',
  'Bihar Intermediate Education Council, Patna',
  'Bihar School Examination Board, Patna',
  'Bihar Sanskrit Shiksha Board, Patna',
  'Bihar Board of Open Schooling & Examination, Patna',
  'Chhattisgarh Board of Secondary Education, Raipur',
  'Chhattisgarh Board of Secondary Education & State Open School, Raipur',
  'Chhattisgarh Madarsa Board',
  'Goa Board of Secondary & Higher Secondary Education',
  'Gujarat Secondary & Higher Secondary Education Board, Gandhinagar',
  'Gujarat State Open School, Gandhinagar',
  'Haryana Board of School Education, Bhiwani',
  'Haryana Open School, Bhiwani',
  'Himachal Pradesh Board of School Education, Dharamshala',
  'Himachal Pradesh State Open School, Kangra',
  'J&K State Board of School Education, Jammu',
  'J&K State Open School, Srinagar',
  'Jharkhand Academic Council, Ranchi',
  'Karnataka Board of Pre-University Education, Bangalore',
  'Karnataka Secondary Education Examination Board, Bangalore',
  'Karnataka Open School, Mysore',
  'Kerala Board of Public Examinations, Thiruvananthapuram',
  'Kerala Board of Higher Secondary Education, Thiruvananthapuram',
  'Kerala State Open School, Thiruvananthapuram',
  'Maharashtra State Board of Secondary and Higher Secondary Education, Pune',
  'Madhya Pradesh Board of Secondary Education, Bhopal',
  'M.P. State Open School, Bhopal',
  'Madhya Pradesh Madarsa Board',
  'Manipur Council of Higher Secondary Education, Imphal',
  'Manipur Board of Secondary Education, Imphal',
  'Meghalaya Board of School Education',
  'Mizoram Board of School Education, Aizawl',
  'Nagaland Board of School Education, Kohima',
  'Odisha Council of Higher Secondary Education, Bhubaneswar',
  'Odisha Board of Secondary Education, Cuttack',
  'Punjab School Education Board, Mohali',
  'Rajasthan Board of Secondary Education, Ajmer',
  'Rajasthan State Open School, Jaipur',
  'Board of Open Schooling and Skill Education, Sikkim',
  'Tamil Nadu Board of Secondary Education, Chennai',
  'Tamil Nadu Board of Higher Secondary Education, Chennai',
  'Tamil Nadu State Open School, Chennai',
  'Telangana Board of Secondary Education, Hyderabad',
  'Telangana Board of International Education, Hyderabad',
  'Telangana Open School Society, Hyderabad',
  'Tripura Board of Secondary Education, Agartala',
  'U.P. Board of High School & Intermediate Education, Allahabad',
  'Board of Madrasa Education, Uttar Pradesh',
  'Uttarakhand Vidhyaleye Shiksha Parishad (UBSE), Ramnagar',
  'West Bengal Board of Secondary Education, Kolkata',
  'West Bengal Council of Higher Secondary Education, Kolkata',
  'West Bengal Council for Rabindra Open Schooling',
  'West Bengal Board of Madrasa Education',
  'Rashtriya Sanskrit Sansthan, New Delhi',
  'Gurukul Kangri Vishwavidyalaya, Haridwar',
  'Directorate of Army Education, New Delhi',
  'Aligarh Muslim University, Aligarh',
  'Jamia Millia Hamdard University',
  'Banasthali Vidyapith, Rajasthan',
  'Jamia Millia Islamia, New Delhi',
  'IGCSE Programme from University of Cambridge',
  'International Baccalaureate - Asia Pacific',
  'Sampurnanand Sanskrit Vishwavidyalaya, Varanasi',
];

/**
 * Complete UGC-recognized universities list (deduplicated by name).
 * Source: UGC official list, 1279 entries.
 */
export const UNIVERSITIES_LIST = [
  '"Kaushalya" the Skill University',
  'A.K.S. University',
  'A.P.G. (Alakh Prakash Goyal) Shimla University',
  'A.P.J. Abdul Kalam Technological University',
  'AAFT University of Media and Arts',
  'Abhilashi University',
  'Abhyuday University',
  'Academy of Maritime Education and Training',
  'Acharya N.G. Ranga Agricultural University',
  'Acharya Nagarjuna University',
  'Acharya Narendra Deva Krishi Evam Prodyogik Vishwavidyalaya',
  'Adamas University',
  'Adani University',
  'Adesh University',
  'Adichunchanagiri University',
  'Adikavi Nannaya University',
  'Aditya University',
  'Agrawan Heritage University',
  'Agriculture University, Jodhpur',
  'Agriculture University, Kota',
  'Ahmedabad University',
  'AIPH University',
  'AISECT University',
  'Ajeenkya D.Y. Patil University',
  'Akal University',
  'Al-Falah University',
  'Al-Karim University',
  'Alagappa University',
  'Alard University',
  'Aliah University',
  'Aligarh Muslim University',
  'Alipurduar University',
  'Alliance University',
  'Amaltas University',
  'Amity University',
  'Amrapali University',
  'Amrita Vishwa Vidyapeetham',
  'Anand Agricultural University',
  'Anant National University',
  'Andhra Kesari University',
  'Andhra Pradesh Fisheries University',
  'Andhra University',
  'Anjaneya University',
  'Anna University',
  'Annamacharya University',
  'Annamalai University',
  'Anurag University',
  'Apeejay Stya University',
  'Apex Professional University',
  'Apex University',
  'Arka Jain University',
  'Arni University',
  'Arunachal Pradesh University',
  'Arunachal University of Studies',
  'Arunodaya University',
  'Aryabhatta Knowledge University',
  'Aryavart University',
  'ASBM University',
  'Ashoka University',
  'Asian International University',
  'Assam Agricultural University',
  'Assam Don Bosco University',
  'Assam Down Town University',
  'Assam Rajiv Gandhi University of Co-operative Management',
  'Assam Science & Technology University',
  'Assam Skill University',
  'Assam University',
  'Assam Veterinary and Fishery University',
  'Assam Women\'s University',
  'Atal Bihari Bajpayee Vishwavidyalaya',
  'Atal Bihari Vajpayee Hindi Vishwavidyalaya',
  'Atal Bihari Vajpayee Medical University',
  'Atal Bihari Vajpayee Skill University',
  'Atal Medical and Research University',
  'Atharva University, Mumbai',
  'ATLAS SKILLTECH UNIVERSITY',
  'Atmiya University',
  'Atria University',
  'Audisankara (Deemed to be University)',
  'Auniati University',
  'AURO University, Surat',
  'Aurora Higher Education and Research Academy',
  'Avantika University',
  'Avinashilingam Institute for Home Science & Higher Education for Women',
  'Awadesh Pratap Singh University',
  'Ayush and Health Sciences University of Chhattisgarh',
  'Azim Premji University',
  'B.L.D.E.',
  'B.S. Abdur Rahman Institute of Science and Technology',
  'Baba Amte Divyang University',
  'Baba Farid University of Health Sciences',
  'Baba Ghulam Shah Badshah University',
  'Baba Mast Nath University',
  'Babasaheb Bhimrao Ambedkar Bihar University',
  'Babasaheb Bhimrao Ambedkar University',
  'Babu Banarasi Das University',
  'Babu Dinesh Singh University',
  'Baddi University of Emerging Sciences & Technology',
  'Bagalkot University',
  'Bahra University',
  'Banaras Hindu University',
  'Banasthai Vidyapith',
  'Banda University of Agriculture & Technology',
  'Bangalore University',
  'Bankura University',
  'Bareilly International University',
  'Barkatullah University',
  'Bengaluru City University',
  'Bengaluru Dr. B. R. Ambedkar School of Economics University',
  'Bengaluru North University',
  'Bennett University',
  'Berhampur University',
  'Bhabha University',
  'Bhagat Phool Singh Mahila Vishwavidyalaya',
  'Bhagwan Mahavir University',
  'Bhagwant Global University',
  'Bhagwant University',
  'Bhaikaka University',
  'Bhakta Kavi Narsinh Mehta University',
  'Bharath Institute of Higher Education & Research',
  'Bharathiar University',
  'Bharathidasan University',
  'Bharati Vidyapeeth',
  'Bharatiya Engineering Science and Technology Innovation University',
  'Bharti Vishwavidyalay',
  'Bhartiya Skill Development University',
  'Bhatkhande Sanskriti Vishwavidyalaya',
  'Bhattadev University',
  'Bhupal Nobles University',
  'Bhupendra Narayan Mandal University',
  'Bidar University',
  'Bidhan Chandra Krishi Vishwavidyalaya',
  'Bihar Agricultural University',
  'Bihar Animal Sciences University',
  'Bihar Engineering University',
  'Bihar Sports University',
  'Bihar University of Health Sciences',
  'Biju Patnaik University of Technology',
  'Bikaner Technical University',
  'Binod Bihari Mahto Koyalanchal University',
  'Bir Tikendrajit University',
  'Birangana Sati Sadhani Rajyik Vishwavidyalaya',
  'Birla Global University',
  'Birla Institute of Technology',
  'Birla Institute of Technology & Science',
  'Birsa Agricultural University',
  'Birsa Munda Tribal University',
  'Biswa Bangla Biswabidyalay',
  'BML Munjal University',
  'Bodoland University',
  'Bongaigaon University',
  'Brainware University',
  'Bundelkhand University',
  'Burdwan University',
  'C. G. C University, Mohali',
  'C. U. Shah University',
  'C. V. Raman Global University',
  'Calcutta University',
  'Calicut University',
  'Capital University',
  'Captain Williamson Sangma State University',
  'Career Point University',
  'Central Agricultural University',
  'Central Institute of Buddhist Studies (CIBS)',
  'Central Institute of Fisheries Education',
  'Central Institute of Higher Tibetan Studies',
  'Central Institute of Technology (CIT)',
  'Central Sanskrit University',
  'Central Tribal University of Andhra Pradesh',
  'Central University of Andhra Pradesh',
  'Central University of Gujarat',
  'Central University of Haryana',
  'Central University of Himachal Pradesh',
  'Central University of Jammu',
  'Central University of Jharkhand',
  'Central University of Karnataka',
  'Central University of Kashmir',
  'Central University of Kerala',
  'Central University of Odisha',
  'Central University of Punjab',
  'Central University of Rajasthan',
  'Central University of South Bihar',
  'Central University of Tamil Nadu',
  'Centurion University of Technology and Management',
  'CEPT University',
  'Chaitanya',
  'Chamarajanagara University',
  'Chanakya National Law University',
  'Chanakya University',
  'Chandigarh University',
  'Chandra Shekhar Azad University of Agriculture & Technology',
  'Charotar University of Science & Technology',
  'Chaudhary Bansi Lal University',
  'Chaudhary Charan Singh University',
  'Chaudhary Devi Lal University',
  'Chaudhary Ranbir Singh University',
  'Chaudhary Sarwan Kumar Himachal Pradesh Krishi Vishvavidyalaya',
  'Chennai Mathematical Institute',
  'Chettinad Academy of Research and Education (CARE)',
  'Chhatrapati Shahu Ji Maharaj University',
  'Chhatrapati Shivaji Maharaj University',
  'Chhattisgarh Kamdhenu Vishwavidyalaya',
  'Chhattisgarh Swami Vivekanad Technical University',
  'Children\'s University',
  'Chinmaya Vishwavidyapeeth',
  'Chirayu University',
  'Chitkara University',
  'Choudhary Charan Singh Haryana Agricultural University',
  'Christ University',
  'Cluster University, Kurnool',
  'Cluster University of Jammu',
  'Cluster University of Srinagar',
  'CMJ University',
  'CMR University',
  'Cochin University of Science & Technology',
  'COEP Technological University',
  'COER University',
  'Cooch Behar Panchanan Barma University',
  'Cotton University',
  'CT University',
  'D Y Patil International University',
  'D. Y. Patil (Deemed)',
  'D. Y. Patil Agriculture and Technical University',
  'D. Y. Patil University',
  'D.A.V University',
  'D.Y Patil Educational Society',
  'Dada Lakhmi Chand State University of Performing and Visual Arts',
  'Dakshin Dinajpur University',
  'Damodaram Sanjivayya National Law University',
  'Darjeeling Hills University',
  'Darshan University',
  'Datta Meghe Institute of Higher Education and Research',
  'Davangere University',
  'Dayalbagh Educational Institute',
  'Dayananda Sagar University',
  'DBS Global University',
  'Deccan College Postgraduate & Research Institute',
  'Deen Bandhu Chhotu Ram University of Sciences & Technology',
  'Deen Dayal Upadhyay Gorakhpur University',
  'Defence Institute of Advanced Technology',
  'Delhi Pharmaceutical Sciences & Research University',
  'Delhi Skill and Entrepreneurship University',
  'Delhi Sports University',
  'Delhi Teachers University',
  'Delhi Technological University',
  'DES Pune University',
  'Desh Bhagat University',
  'Dev Bhoomi Uttarakhand University',
  'Dev Sanskriti Vishwavidyalaya',
  'Devi Ahilya Vishwavidyalaya',
  'Dhanalakshmi Srinivasan University',
  'Dhanamanjuri University',
  'Dharanidhar University',
  'Dharmashastra National Law University',
  'Dharmsinh Desai University',
  'Dhirubhai Ambani University',
  'Diamond Harbour Women\'s University',
  'Dibrugarh University',
  'DIT University',
  'Dnyan Prasad Global University',
  'Doon University',
  'Dr C V Raman University',
  'Dr K N Modi University',
  'Dr Y. S. R. Architecture & Fine Arts University',
  'Dr. A.P.J Abdul Kalam University',
  'Dr. A.P.J. Abdul Kalam Technical University',
  'Dr. Abdul Haq Urdu University',
  'Dr. B. R. Ambedkar University',
  'Dr. B. R. Ambedkar University of Social Sciences',
  'Dr. B.R. Ambedkar National Law University',
  'Dr. B.R. Ambedkar University, Agra',
  'Dr. B.R. Ambedkar University, Delhi',
  'Dr. B.R. Ambedkar Open University',
  'Dr. Babasaheb Ambedkar Marathwada University',
  'Dr. Babasaheb Ambedkar Open University',
  'Dr. Babasaheb Ambedkar Technological University',
  'Dr. Bhimrao Ambedkar Law University',
  'Dr. C.V. Raman University',
  'Dr. D.Y. Patil Vidyapeeth',
  'Dr. Harisingh Gour Vishwavidyalaya',
  'Dr. Homi Bhabha State University',
  'Dr. K. N. Modi University, Modinagar',
  'Dr. M.G.R. Educational and Research Institute',
  'Dr. N.T.R. University of Health Sciences',
  'Dr. P. A. Inamdar University',
  'Dr. Preeti Global University',
  'Dr. Punjabrao Deshmukh Krishi Vidyapeeth',
  'Dr. Rajendra Prasad Central Agricultural University',
  'Dr. Rajendra Prasad National Law University',
  'Dr. Ram Manohar Lohia Awadh University',
  'Dr. Ram Manohar Lohia Institute of Medical Sciences',
  'Dr. Ram Manohar Lohiya National Law University',
  'Dr. Shakuntala Misra National Rehabilitation University',
  'Dr. Shyama Prasad Mukherjee University',
  'Dr. Subhash University',
  'Dr. Vishwanath Karad MIT World Peace University',
  'Dr. Y.S. Parmar University of Horticulture & Forestry',
  'Dr. Y.S.R. Horticultural University',
  'Dravidian University',
  'DRIEMS University',
  'Drs. Kiran & Pallavi Patel Global University (KPGU)',
  'Duke International University',
  'Durga Soren University',
  'EdTech Skills University',
  'Eklavya University',
  'English & Foreign Languages University',
  'Era University',
  'Eternal University',
  'Ethics University',
  'F.S. University',
  'Fakir Mohan University',
  'Film and Television Institute of India',
  'Flame University',
  'Forest Research Institute',
  'Fusion University, Sikkim',
  'Future University',
  'G L A University',
  'G. D. Goenka University',
  'G. H. Raisoni International Skill Tech University',
  'G. M. University',
  'G. S. University',
  'G.B. Pant University of Agriculture & Technology',
  'G.H Raisoni University',
  'G.L.S. University',
  'Galgotias University',
  'Gandhi Institute of Engineering and Technology University (GIET)',
  'Gandhi Institute of Technology and Management (GITAM)',
  'Gandhinagar University',
  'Gangadhar Meher University',
  'Ganpat University',
  'Garden City University',
  'Gati Shakti Vishwavidyalaya',
  'Gauhati University',
  'Gautam Buddha University',
  'Geeta University',
  'Geetanjali University',
  'Girijananda Chowdhury University',
  'GMR Institute of Technology (GMRIT)',
  'GNA University',
  'Goa University',
  'Godavari Global University',
  'Gokhale Institute of Politics & Economics',
  'Gokul Global University',
  'Gondwana University',
  'Gopal Narayan Singh University',
  'Govind Guru Tribal University',
  'Graphic Era',
  'Graphic Era Hill University',
  'GSFC University',
  'Gujarat Ayurveda University',
  'Gujarat Biotechnology University',
  'Gujarat Maritime University',
  'Gujarat National Law University',
  'Gujarat Natural Farming and Organic Agricultural University',
  'Gujarat Technological University',
  'Gujarat University',
  'Gujarat University of Transplantation Sciences',
  'Gujarat Vidyapith',
  'Gulbarga University',
  'Guru Angad Dev Veterinary & Animal Sciences University',
  'Guru Ghasidas Vishwavidyalaya',
  'Guru Gobind Singh Indraprastha Vishwavidyalaya',
  'Guru Jambeshwar University of Science and Technology',
  'Guru Jambheshwar University',
  'Guru Kashi University',
  'Guru Nanak Dev University',
  'Guru Nanak University',
  'Guru Ravidas Ayurved University',
  'Gurucharan University',
  'Gurugram University',
  'Gurukul Kangri Vidyapeeth',
  'Gurukul Vidyapeeth University',
  'Gyanmanjari Innovative University',
  'Gyanodaya University',
  'Gyanveer University',
  'Harcourt Butler Technical University',
  'Harichand Guruchand University',
  'Haridev Joshi University of Journalism and Mass Communication',
  'Haridwar University',
  'Hassan University',
  'Haveri University',
  'Heartfulness Academy of Research and Innovation (HARI)',
  'Hemchand Yadav Vishwavidyalaya',
  'Hemchandracharya North Gujarat University',
  'Hemvati Nandan Bahuguna Garhwal University',
  'Hemvati Nandan Bahuguna Medical Education University',
  'Hidayatullah National Law University',
  'Himachal Pradesh National Law University',
  'Himachal Pradesh Technical University',
  'Himachal Pradesh University',
  'Himalayan University',
  'Hindi University',
  'Hindustan Institute of Technology and Science (HITS)',
  'Homi Bhabha National Institute',
  'Homoeopathy University',
  'HRIT University',
  'Hyderabad (SIND) National Collegiate University',
  'I.E.C. University',
  'I.E.S. University',
  'I.K. Gujaral Punjab Technical University',
  'ICFAI Foundation for Higher Education',
  'ICFAI University',
  'IFTM University',
  'IGNOU (Indira Gandhi National Open University)',
  'IIHMR University',
  'IILM University',
  'IIMT University',
  'IIS (Deemed)',
  'IMS Unison University',
  'India International University of Legal Education and Research',
  'Indian Agricultural Research Institute',
  'Indian Association for the Cultivation of Science (IACS)',
  'Indian Institute for Human Settlements (IIHS)',
  'Indian Institute of Forest Management (IIFM)',
  'Indian Institute of Heritage',
  'Indian Institute of Mass Communication (IIMC)',
  'Indian Institute of Public Health',
  'Indian Institute of Science',
  'Indian Institute of Space Science and Technology',
  'Indian Institute of Teacher Education',
  'Indian Law Institute',
  'Indian Maritime University',
  'Indian Veterinary Research Institute',
  'Indira Gandhi Delhi Technical University for Women',
  'Indira Gandhi Institute of Development Research',
  'Indira Gandhi Krishi Vishwavidyalaya',
  'Indira Gandhi Technological and Medical Science University',
  'Indira Gandhi University',
  'Indira Kala Sangeet Vishwavidyalaya',
  'Indira University',
  'Indraprastha Institute of Information Technology',
  'Indrashil University',
  'Indus International University',
  'Indus University',
  'Institute of Advanced Research',
  'Institute of Advanced Studies in Education',
  'Institute of Chemical Technology',
  'Institute of Infrastructure Technology Research and Management',
  'Institute of Liver and Biliary Sciences (ILBS)',
  'Integral University',
  'International Institute for Population Sciences',
  'International Institute of Information Technology',
  'International Sports University, Maharashtra',
  'Invertis University',
  'ISBM University',
  'Islamic University of Sciences & Technology',
  'ITM (SLS) Baroda University',
  'ITM Skills University',
  'ITM University',
  'ITM Vocational University',
  'J. C. Bose University of Science & Technology, YMCA',
  'J. N. C. T Professional University',
  'J.E.C.R.C University',
  'J.G. University',
  'J.S. University',
  'Jadavpur University',
  'Jagadguru Kripalu University',
  'Jagadguru Ramanandacharya Sanskrit University',
  'Jagadguru Rambhadracharya Divyang State University',
  'Jagan Nath University',
  'Jagannath Barooah University',
  'Jagannath University',
  'Jagran Lakecity University',
  'Jai Minesh Adivasi University',
  'Jai Narain Vyas University',
  'Jai Prakash University',
  'Jain (Deemed)',
  'Jain Vishva Bharati Institute',
  'Jaipur National University',
  'Jamia Hamdard',
  'Jamia Millia Islamia',
  'Jammu University',
  'Jamshedpur Women\'s University',
  'Jananayak Chandrashekhar University',
  'Janardan Rai Nagar Rajasthan Vidyapeeth',
  'Jawaharlal Nehru Centre for Advanced Scientific Research',
  'Jawaharlal Nehru Architecture and Fine Arts University',
  'Jawaharlal Nehru Krishi Vishwavidyalaya',
  'Jawaharlal Nehru Technological University, Hyderabad',
  'Jawaharlal Nehru Technological University, Vizianagram',
  'Jawaharlal Nehru Technological University, Anantapur',
  'Jawaharlal Nehru Technological University, Kakinada',
  'Jawaharlal Nehru University',
  'Jayoti Vidyapeet Women\'s University',
  'Jaypee Institute of Information Technology',
  'Jaypee University',
  'Jaypee University of Engineering & Technology',
  'Jaypee University of Information Technology',
  'Jeppiaar University',
  'Jharkhand Rai University',
  'Jharkhand Raksha Shakti University',
  'Jharkhand State Open University',
  'Jharkhand University of Technology',
  'Jigyasa University',
  'JIS University',
  'Jiwaji University',
  'JK Lakshmipat University',
  'Jodhpur National University',
  'Joy University',
  'JSPM University',
  'JSS Academy of Higher Education & Research',
  'JSS Science & Technology University',
  'JSS University, Noida',
  'Junagadh Agricultural University',
  'K K University',
  'K. D. University, Mathura',
  'K. K. Modi University',
  'K. N. University',
  'K.L.E. Academy of Higher Education and Research',
  'K.M. (Krishna Mohan) University',
  'K.R. Mangalam University',
  'Kadi Sarva Vishwavidyalaya',
  'Kakatiya University',
  'Kalahandi University',
  'Kalasalingam Academy of Research and Education',
  'Kalinga Institute of Industrial Technology',
  'Kalinga Institute of Social Sciences',
  'Kalinga University',
  'Kaloji Narayana Rao University of Health Sciences',
  'Kalyani University',
  'Kamdhenu University',
  'Kameshwar Singh Darbhanga Sanskrit Vishwavidyalaya',
  'Kannada University',
  'Kannur University',
  'Kanyashree University',
  'Karmaveer Bhaurao Patil University',
  'Karnatak University',
  'Karnataka State Law University',
  'Karnataka State Open University',
  'Karnataka Folklore University',
  'Karnataka Samskrit University',
  'Karnataka State Akkamahadevi Women University',
  'Karnataka Veterinary, Animal & Fisheries Science University',
  'Karnavati University',
  'Karpagam Academy of Higher Education',
  'Karunya Institute of Technology and Sciences',
  'Kashmir University',
  'Kaushal Vidya Entrepreneurship, Digital and Skill University',
  'Kavayitri Bahinabai Chadhari North Maharashtra University',
  'Kaveri University',
  'Kavi Kulguru Kalidas Sanskrit Vishwavidyalaya',
  'Kazi Nazrul University',
  'Keladi Shivappa Nayaka University of Agriculture and Horticultural Sciences',
  'Kendriya Hindi Sansthan',
  'Kerala Agricultural University',
  'Kerala Kalamandalam',
  'Kerala University',
  'Kerala University of Digital Sciences Innovation and Technology',
  'Kerala University of Fisheries & Ocean Studies',
  'Kerala University of Health Sciences',
  'Kerala Veterinary & Animal Sciences University',
  'Khaja Bandanawaz University',
  'Khallikote Unitary University',
  'Khalsa University, Amritsar',
  'Khangchendzonga State University',
  'Khongnangthaba University',
  'Khwaja Moinuddin Chishti Language University',
  'King George\'s Medical University',
  'Kishkinda University',
  'KLE Technological University',
  'Kodagu University',
  'Kokrajhar University',
  'Kolhan University',
  'Koneru Lakshmaiah Education Foundation',
  'Konkan Krishi Vidyapeeth',
  'Koppal University',
  'Krantiguru Shyamji Krishna Verma Kachchh University',
  'Krantisurya Tantya Bhil Vishwavidyalaya',
  'Krantivir Tatya Tope Vishwavidyalaya',
  'KREA University',
  'Krishna Institute of Engineering & Technology (KIET)',
  'Krishna Kanta Handiqui State Open University',
  'Krishna University',
  'Krishna Vishwa Vidyapeeth',
  'Krishnaguru Adhyatmik Visvavidyalaya',
  'Kristu Jayanti',
  'KSGH Music and Performing Arts University',
  'Kumar Bhaskar Varma Sanskrit & Ancient Studies University',
  'Kumaun University',
  'Kurukshetra University',
  'Kushabhau Thakre Patrakarita Avam Jansanchar Vishwavidyalaya',
  'Kuvempu University',
  'Lakshmibai National Institute of Physical Education',
  'Lakulish Yoga University',
  'Lala Lajpat Rai University of Veterinary & Animal Sciences',
  'Lalit Narayan Mithila University',
  'Lamrin Tech Skills University',
  'Laxminarayan Innovation Technological (LIT) University',
  'Lingaya\'s Vidyapeeth',
  'LNCT University',
  'LNCT Vidhyapeeth University',
  'Lok Jagruti Kendra University',
  'Lokbharti University for Rural Innovation',
  'Lords University',
  'Lovely Professional University',
  'M. K. University',
  'M.B.M. University',
  'M.P. Bhoj (Open) University',
  'M.S. Ramaiah University of Applied Sciences',
  'M.V.N. University',
  'Maa Pateswari University',
  'Maa Shakumbhari University',
  'Maa Vindhyavasini University',
  'Madan Mohan Malaviya University of Technology',
  'Madanapalle Institute of Technology & Science (MITS)',
  'Madhabdev University',
  'Madhav Institute of Technology and Science',
  'Madhav University',
  'Madhusudan Law University',
  'Madhya Pradesh Medical Science University',
  'Madhyanchal Professional University',
  'Madras University',
  'Madurai Kamraj University',
  'Magadh University',
  'Maganbhai Adenwala Mahagujarat University',
  'Mahakaushal University',
  'Mahapurusha Srimanta Sankaradeva Viswavidyalaya',
  'Maharashtra University of Health Sciences',
  'Maharaj Vinayak Global University',
  'Maharaja Agrasen Himalayan Garhwal University',
  'Maharaja Agrasen University',
  'Maharaja Bir Bikram University',
  'Maharaja Chhatrasal Bundelkhand Vishwavidyalaya',
  'Maharaja Ganga Singh University',
  'Maharaja Krishnakumarsinji Bhavnagar University',
  'Maharaja Ranjit Singh Punjab Technical University',
  'Maharaja Sayajirao University of Baroda',
  'Maharaja Sriram Chandra Bhanja Deo University',
  'Maharaja Suhel Dev State University',
  'Maharaja Surajmal Brij University',
  'Maharana Partap Horticultural University',
  'Maharana Pratap University of Agriculture & Technology',
  'Maharani Cluster University',
  'Maharashtra Animal & Fishery Sciences University',
  'Maharashtra Institute of Technology University of Meghalaya',
  'Maharashtra National Law University, Aurangabad',
  'Maharashtra National Law University, Mumbai',
  'Maharashtra National Law University, Nagpur',
  'Maharashtra State Skills University',
  'Maharishi Arvind University, Jaipur',
  'Maharishi Balmiki Sanskrit University',
  'Maharishi Mahesh Yogi Ramayan University',
  'Maharishi Mahesh Yogi Vedic Vishwavidyalaya',
  'Maharishi Markandeshwar (Deemed)',
  'Maharishi Markandeshwar University',
  'Maharishi University of Information Technology',
  'Maharishi University of Management and Technology',
  'Maharshi Dayanand Saraswati University',
  'Maharshi Dayanand University',
  'Maharshi Panini Sanskrit Evam Vedic Vishwavidyalaya',
  'Mahatma Gandhi Kashi Vidyapeeth',
  'Mahatma Gandhi University (Meghalaya)',
  'Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalaya',
  'Mahatma Gandhi Central University',
  'Mahatma Gandhi Chitrakoot Gramodaya Vishwavidyalaya',
  'Mahatma Gandhi Divyang University',
  'Mahatma Gandhi Rural Development and Panchayat Raj University',
  'Mahatma Gandhi Udyanikee and Vanikee Vishwavidyalaya',
  'Mahatma Gandhi University (West Bengal)',
  'Mahatma Gandhi University (Telangana)',
  'Mahatma Gandhi University (MGU), Sikkim',
  'Mahatma Gandhi University of Medical Sciences & Technology',
  'Mahatma Gandhi University (Kerala)',
  'Mahatma Jyoti Rao Phoole University',
  'Mahatma Jyotiba Phule Rohilkhand University',
  'Mahatma Phule Krishi Vidyapeeth',
  'Mahaveer University',
  'Mahayogi Gorakhnath University',
  'Mahindra University',
  'Major Dhyanchand Sports University',
  'Major S. D. Singh University',
  'Majuli University of Culture',
  'Makhanlal Chaturvedi National University of Journalism & Communication',
  'Malla Reddy (Deemed)',
  'Malla Reddy University',
  'Malla Reddy Vishwavidyapeeth',
  'Malwanchal University',
  'Management and Information Technology University',
  'Manav Bharti University',
  'Manav Rachna International Institute of Research and Studies',
  'Manav Rachna University',
  'Mandsaur University',
  'Mandya University',
  'Mangalayatan University',
  'Mangalore University',
  'Manipal Academy of Higher Education',
  'Manipal University, Jaipur',
  'Manipur International University',
  'Manipur Technical University',
  'Manipur University',
  'Manipur University of Culture',
  'Manonmaniam Sundarnar University',
  'Mansarovar Global University',
  'Marathi Bhasha Vidyapeeth',
  'Marathwada Agricultural University',
  'Martin Luther Christian University',
  'Marwadi University',
  'Marwar Medical University',
  'Mata Gujri University',
  'Mata Tripura Sundari Open University',
  'Matrix SkillTech University',
  'MATS University',
  'Maulana Abul Kalam Azad University of Technology',
  'Maulana Azad National Urdu University',
  'Maulana Azad University',
  'Maulana Mazharul Haque Arabic & Persian University',
  'Maya Devi University',
  'Medhavi Skills University, Sikkim',
  'Medi-Caps University',
  'Meenakshi Academy of Higher Education and Research',
  'Mewar University',
  'MGM Institute of Health Sciences',
  'MGM University',
  'Mind Power University',
  'MIT Art Design and Technology University',
  'MIT Vishwaprayag University, Solapur',
  'Mizoram University',
  'MNR University',
  'Mody University of Science & Technology',
  'Mohammad Ali Jauhar University',
  'Mohan Babu University',
  'Mohanlal Sukhadia University',
  'Monad University',
  'Monark University',
  'Morarji Desai National Institute of Yoga',
  'Mother Teresa Women\'s University',
  'Motherhood University',
  'Mumbai University',
  'Munger University',
  'Murshidabad University',
  'Mysore University',
  'Nagaland University',
  'Nagaon University',
  'Nalanda Open University',
  'Nalanda University',
  'Nanaji Deshmukh Pashu Chikitsa Vigyan Vishwavidyalaya',
  'Narsee Monjee Institute of Management Studies',
  'National Academy of Legal Studies & Research University',
  'National Brain Research Centre',
  'National Dairy Research Institute',
  'National Institute of Advanced Manufacturing Technology (NIAMT)',
  'National Institute of Ayurveda',
  'National Institute of Educational Planning and Administration (NIEPA)',
  'National Institute of Electronics and Information Technology (NIELIT)',
  'National Institute of Technical Teachers Training & Research (NITTTR)',
  'National Law Institute University',
  'National Law School of India University',
  'National Law University, Jodhpur',
  'National Law University, Delhi',
  'National Law University, Odisha',
  'National Law University and Judicial Academy',
  'National Law University Tripura',
  'National Sanskrit University',
  'National Sports University',
  'National University of Advanced Legal Studies (NUALS)',
  'National University of Study & Research in Law',
  'Nava Nalanda Mahavihara',
  'Navrachana University',
  'Navsari Agriculture University',
  'Nayanta University',
  'Nehru Gram Bharati',
  'Netaji Subhas Open University',
  'Netaji Subhas University',
  'Netaji Subhas University of Technology',
  'Netaji Subhash Chandra Bose Institute of Higher Learning',
  'NICMAR University',
  'NIILM University',
  'NIIT University',
  'Nilamber-Pitamber University',
  'NIMS University',
  'NIMT University',
  'Nirma University',
  'Nirwan University',
  'NIST University',
  'NITTE (Deemed)',
  'Nizam\'s Institute of Medical Sciences',
  'NMV University',
  'Noble University',
  'Noida International University',
  'Noorul Islam Centre for Higher Education',
  'North East Adventist University',
  'North East Christian University',
  'North East Frontier Technical University',
  'North Eastern Hill University',
  'North Eastern Regional Institute of Science & Technology',
  'North Lakhimpur University',
  'Nrupathunga University',
  'O.P. Jindal University',
  'Odia University',
  'Odisha State Open University',
  'Odisha University of Agriculture & Technology',
  'Odisha University of Health Sciences',
  'Odisha University of Technology and Research',
  'Om Sterling Global University',
  'OPJS University',
  'Orchid University',
  'Oriental University',
  'Osmania University',
  'P. P. Savani University',
  'P. V. Narsimha Rao Telangana Veterinary University',
  'P.K. University',
  'Pacific Academy of Higher Education & Research (PAHER)',
  'Pacific Medical University',
  'Palamuru University',
  'Pandit Deendayal Energy University',
  'Pandit Deendayal Upadhyaya Shekhawati University',
  'Pandit S N Shukla University',
  'Pandit Sundarlal Sharma (Open) University',
  'Panjab University',
  'Pannadhay University',
  'Parul University',
  'Patliputra University',
  'Patna University',
  'PDM University',
  'People\'s University',
  'Periyar Maniammai Institute of Science & Technology (PMIST)',
  'Periyar University',
  'PES University',
  'PHFI Institute of Public Health Sciences',
  'Phonics University',
  'Pimpri Chinchwad University',
  'Plaksha University',
  'Plastindia International University',
  'Pondicherry University',
  'Ponnaiyah Ramajayam Institute of Science & Technology (PRIST)',
  'Poornima University',
  'Potti Sreeramulu Telugu University',
  'Pragjyotishpur University',
  'Pratap University',
  'Pravara Institute of Medical Sciences',
  'Presidency University, Bengaluru',
  'Presidency University, Kolkata',
  'Prestige Institute of Management and Research (PIMR)',
  'Prestige University',
  'Prof. Rajendra Singh (Rajju Bhaiya) University',
  'Professor Jayashankar Telangana State Agricultural University',
  'Pt. Bhagwat Dayal Sharma University of Health Sciences',
  'Pt. Ravishankar Shukla University',
  'Puducherry Technological University',
  'Punjab Agriculture University',
  'Punjab Engineering College',
  'Punjabi University',
  'Punyashlok Ahilyadevi Holkar Solapur University',
  'Purnea University',
  'Quantum University',
  'R.N.B. Global University',
  'Rabindra Bharati University',
  'Rabindranath Tagore University (Assam)',
  'Rabindranath Tagore University (MP)',
  'Radha Govind University',
  'Raffles University',
  'Rai Technology University',
  'Rai University',
  'Raichur University',
  'Raiganj University',
  'Raj Rishi Bhartrihari Matsya University',
  'Raja Mahendra Pratap Singh State University',
  'Raja Mansingh Tomar Music & Arts University',
  'Raja Shankar Shah University',
  'Rajasthan Technical University',
  'Rajasthan University',
  'Rajasthan University of Health Sciences',
  'Rajasthan University of Veterinary & Animal Sciences',
  'Rajendra University',
  'Rajiv Gandhi National Aviation University',
  'Rajiv Gandhi Prodoyogiki Vishwavidyalaya',
  'Rajiv Gandhi University',
  'Rajiv Gandhi University of Health Science',
  'Rajiv Gandhi University of Knowledge Technologies',
  'Rajju Shroff Rofel University (RSRU)',
  'Rajmata Vijayaraje Scindia Krishi Vishwa Vidyalaya',
  'Ram Krishna Dharmarth Foundation (RKDF) University',
  'Rama Devi Women\'s University',
  'Rama University',
  'Ramakrishna Mission Vivekananda Educational and Research Institute',
  'Ramchandra Chandravansi University',
  'Ramdeobaba University',
  'Ranchi University',
  'Rani Awantibai Lodhi Vishwavidyalaya',
  'Rani Channamma University',
  'Rani Durgavati Vishwavidyalaya',
  'Rani Lakshmi Bai Central Agricultural University',
  'Rani Rashmoni Green University',
  'Ras Bihari Bose Subharti University',
  'Rashtrasant Tukadoji Maharaj Nagpur University',
  'Ravenshaw University',
  'Rayalaseema University',
  'Rayat Bahra Professional University',
  'Rayat Bahra University',
  'Renaissance University',
  'Reva University',
  'RIMT University',
  'Rishihood University',
  'RK University',
  'RKDF University',
  'Rungta International Skills University',
  'RV University',
  'S. K. S. International University',
  'S.R. University',
  'S.R.M Institute of Science and Technology',
  'Sabarmati University',
  'Sadhu Ram Chand Murmu University of Jhargram',
  'Sage University',
  'Sai Nath University',
  'Sai Tirupati University',
  'Sai University',
  'SAM Global University',
  'Sam Higginbottom Institute of Agriculture, Technology & Sciences',
  'Sambalpur University',
  'Sammakka Sarakka Central Tribal University',
  'Sampurnanand Sanskrit Vishwavidyalaya',
  'Sanchi University of Buddhist-Indic Studies',
  'Sandip University',
  'Sangam University',
  'Sanjay Ghodawat University',
  'Sanjeev Agrawal Global Educational University',
  'Sanjivani University',
  'Sankalchand Patel University',
  'Sanskaram University',
  'Sanskriti University',
  'Sant Baba Bhag Singh University',
  'Sant Gadge Baba Amravati University',
  'Sant Gahira Guru Vishwavidyalaya',
  'Sant Longowal Institute of Engineering and Technology',
  'Santosh (Deemed)',
  'Sapthagiri NPS University',
  'Sardar Beant Singh State University',
  'Sardar Bhagwan Singh University',
  'Sardar Krushinagar Dantiwada Agricultural University',
  'Sardar Patel University',
  'Sardar Patel University Mandi',
  'Sardar Patel University of Police, Security & Criminal Justice',
  'Sardar Vallabh Bhai Patel University of Agriculture & Technology',
  'Sardar Vallabhbhai Global University',
  'Sarla Birla University',
  'Saroj International University',
  'Sarvajanik University',
  'Sarvepalli Radhakrishnan University',
  'Satavahana University',
  'Sathyabama Institute of Science and Technology',
  'Satyajit Ray Film and Television Institute (SRFTI)',
  'Saurashtra University',
  'Saveetha Amaravati University',
  'Saveetha Institute of Medical and Technical Sciences',
  'Savitribai Phule Pune University',
  'Scope Global Skills University',
  'SDGI Global University',
  'Seacom Skills University',
  'Shaheed Bhagat Singh State University',
  'Shaheed Mahendra Karma Vishvidyalaya',
  'Shaheed Nandkumar Patel Vishwavidyalaya',
  'Shanmugha Arts Science Technology & Research Academy (SASTRA)',
  'Sharda University',
  'Sharnbasva University',
  'Sher-e-Kashmir University of Agricultural Science & Technology',
  'Shiv Nadar University',
  'Shivaji University',
  'Shobhit Institute of Engineering & Technology',
  'Shobhit University',
  'Shoolini University of Biotechnology and Management Sciences',
  'Shree Guru Gobind Singh Tricentenary University',
  'Shree Om University',
  'Shree Sankaracharaya University of Sanskrit',
  'Shree Somnath Sanskrit University',
  'Shreyarth University',
  'Shri Davara University',
  'Shri Dharmasthala Manjunatheshwara University',
  'Shri Govind Guru University',
  'Shri Guru Ram Rai University',
  'Shri Jagannath Sanskrit Vishwavidyalaya',
  'Shri Jagdish Prasad Jhabarmal Tibrewala University',
  'Shri Kallaji Vedic Vishvavidyalaya',
  'Shri Khushal Das University',
  'Shri Krishna AYUSH University',
  'Shri Krishna University',
  'Shri Lal Bahadur Shastri National Sanskrit University',
  'Shri Mata Vaishno Devi University',
  'Shri Ramasamy Memorial University, Sikkim',
  'Shri Ramswaroop Memorial University',
  'Shri Rawatpura Sarkar University',
  'Shri Shankaracharya Professional University',
  'Shri Vaishnav Vidyapeeth Vishwavidyalaya',
  'Shri Venkateshwara University',
  'Shri Vishwakarma Skill University',
  'Shridhar University',
  'Shubham University',
  'Shyam University',
  'Sibsagar University',
  'Siddharth University',
  'Siddhartha Academy of Higher Education',
  'Sidho-Kanho-Birsha University',
  'Sido Kanhu Murmu University',
  'Sigma University',
  'Sikkim Alpine University',
  'Sikkim Global Technical University',
  'Sikkim International University',
  'Sikkim Manipal University',
  'Sikkim Medical Science University',
  'Sikkim National Law University',
  'Sikkim Organic Agriculture University',
  'Sikkim Professional University',
  'Sikkim Sardar Patel University',
  'Sikkim Skill University',
  'Sikkim University',
  'Siksha \'O\' Anusandhan',
  'Silicon University',
  'Silver Oak University',
  'Sindhu Central University',
  'Singhania University',
  'Sir J.J. School of Art, Architecture & Design, Mumbai',
  'Sir Padmapat Singhania University',
  'Sister Nivedita University',
  'SKIPS University',
  'Smt. Manjira Devi University',
  'Smt. Nathibai Damodar Thackersey Women\'s University',
  'Soban Singh Jeena University',
  'Somaiya Vidyavihar University',
  'Sona Devi University',
  'South Asian University',
  'Sparsh Himalaya University',
  'Spicer Adventist University',
  'Sports University of Haryana',
  'Sree Narayanguru Open University',
  'Sreenidhi University',
  'Sri Aurobindo University',
  'Sri Balaji University, Pune',
  'Sri Balaji Vidyapeeth',
  'Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya',
  'Sri Dev Suman Uttarakhand Vishwavidyalaya',
  'Sri Devraj Urs Academy of Higher Education and Research',
  'Sri Guru Granth Sahib World University',
  'Sri Guru Ram Das University of Health Sciences',
  'Sri Guru Teg Bahadur State University of Law',
  'Sri Jagadhguru Murugarajendra University',
  'Sri Karan Narendra Agriculture University',
  'Sri Konda Laxman Telangana State Horticultural University',
  'Sri Krishnadevaraya University',
  'Sri Padmavati Mahila Vishwavidyalayam',
  'Sri Ramachandra Institute of Higher Education and Research',
  'Sri Sai University',
  'Sri Sathya Sai Institute of Higher Learning',
  'Sri Sathya Sai University for Human Excellence',
  'Sri Satya Sai University of Technology & Medical Sciences',
  'Sri Siddhartha Academy of Higher Education',
  'Sri Sri Aniruddhdeva Sports University',
  'Sri Sri University',
  'Sri Venkateshwara University (Sikkim)',
  'Sri Venkateswara Institute of Medical Sciences',
  'Sri Venkateswara University',
  'Sri Venkateswara Vedic University',
  'Sri Venkateswara Veterinary University',
  'Sri Venkateswaraa University',
  'Srimanta Sankaradeva University of Health Sciences',
  'Srinath University',
  'Srinivas University',
  'SRM University, AP',
  'SRM University, Haryana',
  'St. Aloysius',
  'St. Joseph University',
  'St. Joseph\'s University, Bengaluru',
  'St. Peter\'s Institute of Higher Education and Research',
  'St. Xavier\'s University, Kolkata',
  'Starex University',
  'Sumandeep Vidyapeeth',
  'Sunrise University',
  'Surajmal University',
  'Surendranagar University',
  'Suresh Gyan Vihar University',
  'Sushant University',
  'Swami Keshwanand Rajasthan Agricultural University',
  'Swami Rama Himalayan University',
  'Swami Ramanand Teerth Marathwada University',
  'Swami Vivekanand University',
  'Swami Vivekananda Subharti University',
  'Swami Vivekananda University (West Bengal)',
  'Swami Vivekananda Yoga Anusandhana Samsthana',
  'Swaminarayan University',
  'Swarnim Gujarat Sports University',
  'Swarnim Startup & Innovation University',
  'Symbiosis International University',
  'Symbiosis Skills and Professional University',
  'Symbiosis University of Applied Sciences (SUAS)',
  'T. S. Mishra University',
  'T.M. Bhagalpur University',
  'Takshashila University',
  'Tamil Nadu Fisheries University',
  'Tamil Nadu Open University',
  'Tamil Nadu Physical Education and Sports University',
  'Tamil Nadu Teacher Education University',
  'Tamil University',
  'Tamilnadu Agricultural University',
  'Tamilnadu Dr. Ambedkar Law University',
  'Tamilnadu Dr. M.G.R. Medical University',
  'Tamilnadu National Law University',
  'Tamilnadu Veterinary & Animal Sciences University',
  'Tantia University',
  'Tata Institute of Fundamental Research',
  'Tata Institute of Social Sciences',
  'TCG CREST',
  'Team Lease Skills University',
  'Techno Global University',
  'Techno India University',
  'Teerthanker Mahaveer University',
  'Telangana University',
  'TERI School of Advanced Studies',
  'Tezpur University',
  'Thapar Institute of Engineering & Technology',
  'The Apollo University',
  'The Aryavart International University',
  'The Assam Kaziranga University',
  'The Assam Royal Global University',
  'The Bengal Engineering & Science University',
  'The Charutar Vidya Mandal (CVM) University',
  'The Dhamma Dipa International Buddhist University',
  'The Dr. Sarvepalli Radhakrishnan Rajasthan Ayurved University',
  'The Gandhigram Rural Institute',
  'The Global Open University',
  'The Global University',
  'The Glocal University',
  'The ICFAI University',
  'The ICFAI University Sikkim',
  'The Indira Gandhi National Tribal University',
  'The Institute of Chartered Financial Analysts of India University',
  'The LNM Institute of Information Technology',
  'The Maharaja Bhupinder Singh Punjab Sports University',
  'The National Law University of Meghalaya',
  'The Neotia University',
  'The Northcap University',
  'The Rajasthan University of Veterinary and Animal Sciences (Jobner)',
  'The Rajiv Gandhi National University of Law',
  'The Sanskrit College and University',
  'The SVKM NMIMS Global University',
  'The Tamil Nadu Dr. J Jayalalithaa Music and Fine Arts University',
  'The University of North West Himalayas',
  'The University of Trans-Disciplinary Health Sciences and Technology',
  'The West Bengal National University of Juridical Science',
  'The West Bengal University of Health Sciences',
  'Thiruvalluvar University',
  'Thunchath Ezhuthachan Malayalam University',
  'Tilak Maharashtra Vidyapeeth',
  'Transstadia University',
  'Trident University of Applied Sciences, Sikkim',
  'Tripura University',
  'Tumkur University',
  'U.P. Pandit Deen Dayal Upadhyaya Pashu Chikitsa Vigyan Vishwavidhyalaya',
  'U.P. Rajarshi Tandon Open University',
  'U.P. King George\'s University of Dental Sciences',
  'UKA Tarsadia University',
  'United University',
  'Universal AI University',
  'Universal SkillTech University',
  'University of Agricultural Sciences, Raichur',
  'University of Agricultural Sciences, Bangalore',
  'University of Agricultural Sciences, Dharwad',
  'University of Agricultural Sciences, Mandya',
  'University of Allahabad',
  'University of Delhi',
  'University of Engineering & Management',
  'University of Gour Banga',
  'University of Horticultural Sciences',
  'University of Hyderabad',
  'University of Kota',
  'University of Ladakh',
  'University of Lucknow',
  'University of North Bengal',
  'University of Patanjali',
  'University of Petroleum and Energy Studies',
  'University of Science & Technology, Meghalaya',
  'University of Technology',
  'University of Visvesvaraya College of Engineering',
  'UPL University of Sustainable Technology',
  'Usha Martin University',
  'Utkal University',
  'Utkal University of Culture',
  'Uttar Banga Krishi Vishwavidyalaya',
  'Uttar Pradesh University of Medical Sciences',
  'Uttarakhand Ayurved University',
  'Uttarakhand Open University',
  'Uttarakhand Sanskrit University',
  'Uttarakhand State Sports University',
  'Uttarakhand Technical University',
  'Uttaranchal University',
  'Vanita Vishram Women\'s University',
  'Vardhman Mahaveer Open University',
  'Varun Arjun University',
  'Vasireddy Venkatadri International Technological University',
  'Veer Bahadur Singh Purvanchal University',
  'Veer Chandra Singh Garhwali Uttarakhand University of Horticulture & Forestry',
  'Veer Kunwar Singh University',
  'Veer Narmad South Gujarat University',
  'Veer Surendra Sai Institute of Medical Science and Research',
  'Veer Surendra Sai University of Technology',
  'Veeranari Chakali Ilamma Women\'s University',
  'Vel Tech Rangarajan Dr. Sagunthala R & D Institute of Science and Technology',
  'Vellore Institute of Technology',
  'VELS Institute of Science Technology & Advanced Studies (VISTAS)',
  'Veltech University',
  'Venkateshwara Open University',
  'Visvesvaraya Technological University',
  'Vidhyadeep University',
  'Vidya Sagar University',
  'Vidya University',
  'Vidyashilp University',
  'Vignan\'s Foundation for Science, Technology and Research',
  'Vijayanagara Sri Krishnadevaraya University',
  'Vijaybhoomi University',
  'Vikram Dev University, Jeypore',
  'Vikram University',
  'Vikrama Simhapuri University',
  'Vikrant University',
  'Vinayaka Mission\'s Research Foundation',
  'Vinoba Bhave University',
  'Vishvakarma Skills University',
  'Vishwakarma University',
  'Visva Bharati',
  'VIT Bhopal University',
  'VIT-AP University',
  'Vivek University',
  'Vivekananda Global University',
  'West Bengal State University',
  'West Bengal University of Animal and Fishery Sciences',
  'West Bengal University of Teachers, Training, Education Planning and Administration',
  'William Carey University',
  'World University of Design',
  'Woxsen University',
  'Xavier University, Digha Ghat',
  'XIM University',
  'Yashwant Rao Chavan Maharashtra Open University',
  'YBN University',
  'Yenepoya',
  'Yogi Vemana University',
  'Young India Skills University',
];

/** Check if a value is from the predefined list */
export function isPredefinedBoard(value: string): boolean {
  return BOARDS_LIST.some(b => b.toLowerCase() === value.toLowerCase());
}

export function isPredefinedUniversity(value: string): boolean {
  return UNIVERSITIES_LIST.some(u => u.toLowerCase() === value.toLowerCase());
}
