import { useState } from "react";
import { Button } from "@/components/ui/button";
import { CBSE_CATEGORY_LABELS, CBSE_EXAM_STATUS_LABELS, evaluatePolicyPaper, type CbseConfiguration, type CbseMark, type CbsePaper, type CbseWorkspace } from "@/lib/cbseExams";
import { AcademicField, AcademicPanel, academicInput, markFromInput } from "./AcademicFields";
import type { AcademicAction } from "./PolicyEditor";

const pageSize = 25;
function PaperEntry({ paper, workspace, disabled, onAction }: { paper: CbsePaper; workspace: CbseWorkspace; disabled: boolean; onAction: AcademicAction }) {
  const students = workspace.students.filter(s => s.applicable_subject_ids.includes(paper.subject_id));
  const [rows, setRows] = useState<Record<string, CbseMark>>(() => Object.fromEntries(students.map(s => [s.id, s.marks[paper.id] || { status: "present", scores: {}, remarks: null }])));
  const [page, setPage] = useState(0);
  const [reason, setReason] = useState("");
  const [dirty, setDirty] = useState(false);
  const readOnly = disabled || !paper.can_enter || !!paper.locked_at || workspace.exam.status !== "open";
  const setRow = (id: string, row: Partial<CbseMark>) => { setDirty(true); setRows(current => ({ ...current, [id]: { ...current[id], ...row } })); };
  const save = async () => { if (await onAction("save_marks", { paper_id: paper.id, rows: students.map(s => ({student_id:s.id,...rows[s.id]})) })) setDirty(false); };
  const rule = workspace.policy.rules.subjects.find(s => s.subject_id === paper.subject_id);
  const complete = students.filter(s => rule && evaluatePolicyPaper(rule, rows[s.id], workspace.policy.rules).complete).length;
  return <AcademicPanel title={`${paper.name} · ${paper.locked_at ? "Locked" : "Entry open"}`} description={`${complete} / ${students.length} applicable students complete. Blank marks remain missing; enter 0 for a scored zero.`}>
    <div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left border-b"><th className="p-2">Student</th><th className="p-2">Status</th>{paper.components.map(c => <th key={c.key} className="p-2">{c.label} / {c.max}</th>)}<th className="p-2">Subject remarks</th></tr></thead><tbody>{students.slice(page * pageSize, (page + 1) * pageSize).map(s => <tr key={s.id} className="border-b"><td className="p-2 min-w-40">{s.name}<span className="block text-xs text-muted-foreground">{s.admission_no}</span></td><td className="p-2"><select aria-label={`${s.name} status`} className={`${academicInput} min-w-28`} disabled={readOnly} value={rows[s.id].status} onChange={e => setRow(s.id, { status: e.target.value as CbseMark["status"], scores: {} })}><option value="present">Present</option><option value="absent">Absent</option><option value="exempt">Exempt</option></select></td>{paper.components.map(c => <td key={c.key} className="p-2"><input aria-label={`${s.name} ${c.label}`} type="number" min="0" max={c.max} step="0.01" disabled={readOnly || rows[s.id].status !== "present"} className={`${academicInput} min-w-24`} value={rows[s.id].scores[c.key] ?? ""} onChange={e => setRow(s.id, { scores: { ...rows[s.id].scores, [c.key]: markFromInput(e.target.value) } })} /></td>)}<td className="p-2"><input aria-label={`${s.name} subject remarks`} className={`${academicInput} min-w-40`} disabled={readOnly} value={rows[s.id].remarks || ""} onChange={e => setRow(s.id, {remarks:e.target.value})} /></td></tr>)}</tbody></table></div>
    <Pager page={page} count={students.length} setPage={setPage} />
    {paper.can_enter && !paper.locked_at && workspace.exam.status === "open" && <div className="flex flex-wrap items-center gap-3"><Button disabled={disabled || !dirty} onClick={save}>Save marks</Button><Button variant="outline" disabled={disabled || dirty || complete !== students.length || !students.length} onClick={() => onAction("lock_paper", {paper_id:paper.id})}>Lock paper</Button>{dirty && <span className="text-xs text-muted-foreground">Save changes before locking.</span>}</div>}
    {paper.locked_at && (workspace.capabilities.class_teacher || workspace.capabilities.review) && ["open","class_review","principal_review"].includes(workspace.exam.status) && <div className="flex gap-3 flex-wrap items-end"><AcademicField label={`${paper.name} return reason`}><input className={academicInput} disabled={disabled} value={reason} onChange={e => setReason(e.target.value)} /></AcademicField><Button variant="outline" disabled={disabled || !reason.trim()} onClick={() => onAction("return_paper", {paper_id:paper.id,remarks:reason})}>Return paper for correction</Button></div>}
  </AcademicPanel>;
}

export function Pager({page,count,setPage}:{page:number;count:number;setPage:(page:number)=>void}) {
  if (count <= pageSize) return null;
  return <div className="flex gap-3 items-center text-sm"><Button variant="outline" size="sm" disabled={page===0} onClick={()=>setPage(page-1)}>Previous</Button><span>Page {page+1} of {Math.ceil(count/pageSize)}</span><Button variant="outline" size="sm" disabled={(page+1)*pageSize>=count} onClick={()=>setPage(page+1)}>Next</Button></div>;
}

function StudentReview({workspace,disabled,onAction}:{workspace:CbseWorkspace;disabled:boolean;onAction:AcademicAction}) {
  const [rows,setRows]=useState(()=>workspace.students.map(s=>({student_id:s.id,attendance_present:s.attendance_present,attendance_working_days:s.attendance_working_days,remarks:s.remarks||""})));
  const [page,setPage]=useState(0);
  const [dirty,setDirty]=useState(false);
  const writable=(workspace.capabilities.class_teacher||workspace.capabilities.manage)&&["open","class_review"].includes(workspace.exam.status);
  return <AcademicPanel title="Attendance and class-teacher remarks" description="Required for each student before Principal review. Attendance covers the reporting period."><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left"><th className="p-2">Student</th><th className="p-2">Present days</th><th className="p-2">Working days</th><th className="p-2">Remarks</th></tr></thead><tbody>{rows.slice(page*pageSize,(page+1)*pageSize).map(row=><tr key={row.student_id} className="border-t"><td className="p-2 min-w-40">{workspace.students.find(s=>s.id===row.student_id)?.name}</td>{(["attendance_present","attendance_working_days"] as const).map(key=><td key={key} className="p-2"><input aria-label={`${row.student_id} ${key === "attendance_present" ? "present days" : "working days"}`} type="number" min="0" step="1" className={`${academicInput} min-w-24`} disabled={disabled||!writable} value={row[key]??""} onChange={e=>{setDirty(true);setRows(rs=>rs.map(r=>r.student_id===row.student_id?{...r,[key]:markFromInput(e.target.value)}:r));}} /></td>)}<td className="p-2"><textarea aria-label={`${row.student_id} class remarks`} className={`${academicInput} min-w-60`} disabled={disabled||!writable} value={row.remarks} onChange={e=>{setDirty(true);setRows(rs=>rs.map(r=>r.student_id===row.student_id?{...r,remarks:e.target.value}:r));}} /></td></tr>)}</tbody></table></div><Pager page={page} count={rows.length} setPage={setPage}/>{writable&&<Button disabled={disabled||!dirty} onClick={async()=>{if(await onAction("student_details",{rows}))setDirty(false);}}>Save attendance and remarks</Button>}</AcademicPanel>;
}

function DraftConfiguration({workspace,configuration,disabled,onAction}:{workspace:CbseWorkspace;configuration:CbseConfiguration;disabled:boolean;onAction:AcademicAction}) {
  const [policyId,setPolicyId]=useState(workspace.exam.policy_id);
  const [cutoff,setCutoff]=useState(workspace.exam.fee_cutoff);
  const [teachers,setTeachers]=useState<Record<string,string>>(()=>Object.fromEntries(workspace.papers.map(p=>[p.subject_id,p.teacher_user_id])));
  const [sourceIds,setSourceIds]=useState(workspace.sources.map(s=>s.source_exam_id));
  const [roster,setRoster]=useState(()=>workspace.students.map(s=>({student_id:s.id,applicable_subject_ids:s.applicable_subject_ids})));
  const [page,setPage]=useState(0);
  const policies=configuration.policies.filter(p=>p.course_id===workspace.exam.course_id&&p.session_id===workspace.exam.session_id&&p.status==="approved");
  const selected=policies.find(p=>p.id===policyId);
  const sources=configuration.exams.filter(e=>e.course_id===workspace.exam.course_id&&e.session_id===workspace.exam.session_id&&e.section===workspace.exam.section&&e.category!=="annual"&&["approved","released"].includes(e.status));
  return <AcademicPanel title="Draft configuration" description="Save configuration changes before editing the roster. Opening entry freezes these choices."><fieldset disabled={disabled||!workspace.capabilities.manage} className="space-y-4"><div className="grid sm:grid-cols-2 gap-3"><AcademicField label="Policy version"><select className={academicInput} value={policyId} onChange={e=>{setPolicyId(e.target.value);setTeachers({});}}>{policies.map(p=><option key={p.id} value={p.id}>{p.name} · v{p.version}</option>)}</select></AcademicField><AcademicField label="Fee cutoff"><input type="date" className={academicInput} value={cutoff} onChange={e=>setCutoff(e.target.value)}/></AcademicField></div>
    {workspace.exam.category!=="annual"?selected?.rules.subjects.map(s=><AcademicField key={s.subject_id} label={`${configuration.subjects.find(x=>x.id===s.subject_id)?.name||"Subject"} teacher`}><select className={academicInput} value={teachers[s.subject_id]||""} onChange={e=>setTeachers(t=>({...t,[s.subject_id]:e.target.value}))}><option value="">Exclude this paper</option>{configuration.staff.map(t=><option value={t.user_id} key={t.user_id}>{t.name}</option>)}</select></AcademicField>):<div className="space-y-2">{sources.map(source=><label key={source.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={sourceIds.includes(source.id)} onChange={e=>setSourceIds(ids=>e.target.checked?[...ids,source.id]:ids.filter(id=>id!==source.id))}/>{source.name} · revision {source.revision}</label>)}</div>}
    <Button variant="outline" onClick={()=>onAction("configure_exam",{policy_id:policyId,fee_cutoff:cutoff,...(workspace.exam.category==="annual"?{source_exam_ids:sourceIds}:{papers:Object.entries(teachers).filter(([id,teacher])=>teacher&&selected?.rules.subjects.some(s=>s.subject_id===id)).map(([subject_id,teacher_user_id])=>({subject_id,teacher_user_id}))})})}>Save exam configuration</Button>
    <h3 className="font-medium text-sm">Student subject applicability</h3><p className="text-xs text-muted-foreground">Review electives individually. Students use class, section and session, without a batch.</p><div className="space-y-3">{roster.slice(page*pageSize,(page+1)*pageSize).map(row=><div key={row.student_id} className="border rounded-lg p-3"><p className="text-sm font-medium mb-2">{workspace.students.find(s=>s.id===row.student_id)?.name}</p><div className="flex flex-wrap gap-3">{workspace.policy.rules.subjects.map(subject=><label key={subject.subject_id} className="text-sm flex gap-2 items-center"><input type="checkbox" checked={row.applicable_subject_ids.includes(subject.subject_id)} onChange={e=>setRoster(rs=>rs.map(r=>r.student_id!==row.student_id?r:{...r,applicable_subject_ids:e.target.checked?[...r.applicable_subject_ids,subject.subject_id]:r.applicable_subject_ids.filter(id=>id!==subject.subject_id)}))}/>{configuration.subjects.find(s=>s.id===subject.subject_id)?.name||"Subject"}</label>)}</div></div>)}</div><Pager page={page} count={roster.length} setPage={setPage}/><Button onClick={()=>onAction("configure_roster",{students:roster})}>Save subject applicability</Button></fieldset></AcademicPanel>;
}

function ReportsReview({workspace,disabled,onAction}:{workspace:CbseWorkspace;disabled:boolean;onAction:AcademicAction}) {
  const [selected,setSelected]=useState<string[]>([]);
  const [reason,setReason]=useState("");
  const [preview,setPreview]=useState("");
  const [page,setPage]=useState(0);
  const report=workspace.reports.find(r=>r.id===preview);
  const current=workspace.reports.filter(r=>r.revision===workspace.exam.revision&&r.status!=="withdrawn");
  return <AcademicPanel title="Reports, fee clearance and exceptions" description="Academic approval and release are separate. Fee eligibility is checked again on every final download."><AcademicField label="Release or fee-exception remarks"><textarea className={academicInput} disabled={disabled} value={reason} onChange={e=>setReason(e.target.value)}/></AcademicField><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left"><th className="p-2">Release</th><th className="p-2">Student</th><th className="p-2">Current fee status</th><th className="p-2">Report</th><th className="p-2">Exception</th></tr></thead><tbody>{workspace.students.slice(page*pageSize,(page+1)*pageSize).map(s=>{const latest=current.find(r=>r.student_id===s.id);const exception=workspace.exceptions.find(e=>e.student_id===s.id&&e.revision===workspace.exam.revision&&e.fee_cutoff===workspace.exam.fee_cutoff&&["pending","approved"].includes(e.status));return <tr className="border-t" key={s.id}><td className="p-2"><input aria-label={`Release ${s.name}`} type="checkbox" disabled={disabled||!workspace.capabilities.review||!latest||latest.status!=="approved"} checked={selected.includes(s.id)} onChange={e=>setSelected(ids=>e.target.checked?[...ids,s.id]:ids.filter(id=>id!==s.id))}/></td><td className="p-2">{s.name}</td><td className="p-2">{s.fee.status==="clear"?"Clear":s.fee.status==="due"?`Due ₹${s.fee.due?.toFixed(2)}`:"Unresolved — office review required"}</td><td className="p-2">{latest?<Button size="sm" variant="outline" onClick={()=>setPreview(latest.id)}>Preview · {latest.status}</Button>:"Awaiting approval"}</td><td className="p-2">{exception?<span>{exception.status}</span>:latest&&s.fee.status!=="clear"?<Button size="sm" variant="outline" disabled={disabled||!reason.trim()||!(workspace.capabilities.manage||workspace.capabilities.class_teacher||workspace.capabilities.review)} onClick={()=>onAction("request_exception",{student_id:s.id,remarks:reason})}>Request exception</Button>:"—"}</td></tr>;})}</tbody></table></div><Pager page={page} count={workspace.students.length} setPage={setPage}/>{workspace.capabilities.review&&<Button disabled={disabled||!reason.trim()||!selected.length} onClick={()=>onAction("release",{student_ids:selected,remarks:reason})}>Release selected reports ({selected.length})</Button>}
    {report&&<div className="rounded-lg border p-5 space-y-3"><div className="flex justify-between gap-3"><h3 className="font-semibold">Staff preview · revision {report.revision} · {report.status}</h3><Button variant="ghost" onClick={()=>setPreview("")}>Close preview</Button></div><p className="text-xs text-muted-foreground">For academic review. This screen is not a released report PDF.</p><h4 className="font-medium">{report.snapshot.school.name} · {report.snapshot.title}</h4><p>{report.snapshot.student.name} · {report.snapshot.student.course_name}</p><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left"><th>Subject</th><th>Components</th><th>Total</th><th>Grade</th><th>Outcome</th></tr></thead><tbody>{report.snapshot.subjects.map(s=><tr className="border-t" key={s.subject_id}><td className="py-2">{s.name}</td><td>{s.components.map(c=>`${c.label}: ${c.score??"—"}/${c.max}`).join(" · ")}</td><td>{s.obtained??"—"}/{s.max}</td><td>{s.grade??"—"}</td><td>{s.status!=="present"?s.status:s.passed===false?"Below threshold":s.passed?"Pass":"—"}</td></tr>)}</tbody></table></div><p>Overall: {report.snapshot.summary.obtained}/{report.snapshot.summary.max} · {report.snapshot.summary.grade} · {report.snapshot.summary.result}</p><p>Attendance: {report.snapshot.attendance.present}/{report.snapshot.attendance.working_days}</p><p>{report.snapshot.remarks}</p><p className="text-xs text-muted-foreground">Approved by {report.snapshot.approval.name} · {report.snapshot.approval.approved_at} · {report.snapshot.approval.remarks}</p><p className="text-xs">School performance report; does not determine Board grades or Board-exam eligibility.</p></div>}
    {workspace.exceptions.length>0&&<div className="space-y-3"><h3 className="font-medium text-sm">Exception history</h3>{workspace.exceptions.map(e=><div className="border rounded-lg p-3 space-y-2 text-sm" key={e.id}><p>{workspace.students.find(s=>s.id===e.student_id)?.name} · revision {e.revision} · {e.status} · cutoff {e.fee_cutoff}</p><p>Request: {e.request_remarks}</p>{e.review_remarks&&<p>Review: {e.review_remarks}</p>}<p className="text-xs text-muted-foreground">Requested {e.created_at} · requester {e.requested_by}{e.reviewed_by&&` · reviewer ${e.reviewed_by}`}</p>{workspace.capabilities.review&&e.revision===workspace.exam.revision&&<div className="flex flex-wrap gap-2">{(e.status==="pending"?["approved","rejected"]:e.status==="approved"?["revoked"]:[]).map(decision=><Button key={decision} variant="outline" size="sm" disabled={disabled||!reason.trim()} onClick={()=>onAction("review_exception",{exception_id:e.id,decision,remarks:reason})}>{decision==="approved"?"Approve exception":decision==="rejected"?"Reject exception":"Revoke exception"}</Button>)}</div>}</div>)}</div>}
    <details><summary className="cursor-pointer text-sm font-medium">All report revisions ({workspace.reports.length})</summary><div className="mt-3 flex flex-wrap gap-2">{workspace.reports.map(r=><Button key={r.id} variant="outline" size="sm" onClick={()=>setPreview(r.id)}>{r.snapshot.student.name} · v{r.revision} · {r.status}</Button>)}</div></details>
  </AcademicPanel>;
}

export function ExamWorkspace({workspace,configuration,disabled,onAction,onChangeClassTeacher}:{workspace:CbseWorkspace;configuration:CbseConfiguration;disabled:boolean;onAction:AcademicAction;onChangeClassTeacher?:(teacherUserId:string,remarks:string)=>Promise<boolean>}) {
  const [remarks,setRemarks]=useState("");
  const [classTeacher,setClassTeacher]=useState("");
  const [reopenDraft,setReopenDraft]=useState(false);
  const [reopenPaper,setReopenPaper]=useState("");
  const {exam,capabilities}=workspace;
  const canClass=capabilities.class_teacher||capabilities.manage;
  const selectedRule=(subjectId:string)=>workspace.policy.rules.subjects.find(s=>s.subject_id===subjectId);
  const failures=workspace.students.filter(s=>workspace.papers.some(p=>s.applicable_subject_ids.includes(p.subject_id)&&selectedRule(p.subject_id)&&evaluatePolicyPaper(selectedRule(p.subject_id)!,s.marks[p.id],workspace.policy.rules).passed===false)).length;
  return <div className="space-y-5"><AcademicPanel title={exam.name} description={`${CBSE_EXAM_STATUS_LABELS[exam.status]} · Revision ${exam.revision} · ${exam.starts_on} – ${exam.ends_on} · Fee cutoff ${exam.fee_cutoff}`}><div className="grid gap-3 sm:grid-cols-3 text-sm"><p>{workspace.students.length} students</p><p>{workspace.papers.filter(p=>p.locked_at).length}/{workspace.papers.length} papers locked</p><p>{failures} students with below-threshold marks</p></div><p className="text-xs text-muted-foreground">Policy: {workspace.policy.name} · v{workspace.policy.version}. X/XII reports are school performance reports.</p><AcademicField label="Workflow remarks"><textarea disabled={disabled} className={academicInput} value={remarks} onChange={e=>setRemarks(e.target.value)} placeholder="Required for review decisions, corrections and release"/></AcademicField><div className="flex flex-wrap gap-2">
    {exam.status==="draft"&&capabilities.manage&&<Button disabled={disabled} onClick={()=>onAction("open",{})}>Open marks entry</Button>}
    {exam.status==="open"&&canClass&&<Button disabled={disabled||(exam.category!=="annual"&&workspace.papers.some(p=>!p.locked_at))} onClick={()=>onAction("submit_class_review",{})}>Submit to class-teacher review</Button>}
    {exam.status==="class_review"&&canClass&&<Button disabled={disabled||!remarks.trim()} onClick={()=>onAction("submit_principal_review",{remarks})}>Submit to Principal review</Button>}
    {exam.status==="principal_review"&&capabilities.review&&<Button disabled={disabled||!remarks.trim()} onClick={()=>onAction("approve",{remarks})}>Approve academic reports</Button>}
    {["approved","released"].includes(exam.status)&&capabilities.review&&<Button disabled={disabled||!remarks.trim()} onClick={()=>onAction("release",{remarks})}>Release all current reports</Button>}
    {["draft","open"].includes(exam.status)&&capabilities.manage&&<Button variant="outline" disabled={disabled||!remarks.trim()} onClick={()=>onAction("cancel",{remarks})}>Cancel exam</Button>}
    </div>{onChangeClassTeacher&&capabilities.manage&&!["approved","released","cancelled"].includes(exam.status)&&<div className="border-t pt-4 space-y-3"><h3 className="text-sm font-medium">Class teacher</h3><p className="text-xs text-muted-foreground">Current: {configuration.staff.find(s=>s.user_id===exam.class_teacher_user_id)?.name||"—"}. The class teacher handles attendance, remarks and the review hand-off.</p><div className="flex flex-wrap gap-3 items-end"><AcademicField label="Change to"><select aria-label="Change class teacher" className={academicInput} disabled={disabled} value={classTeacher} onChange={e=>setClassTeacher(e.target.value)}><option value="">Choose staff</option>{configuration.staff.map(s=><option key={s.user_id} value={s.user_id}>{s.name}</option>)}</select></AcademicField><Button variant="outline" disabled={disabled||!classTeacher||!remarks.trim()} onClick={async()=>{if(await onChangeClassTeacher(classTeacher,remarks))setClassTeacher("");}}>Change class teacher</Button>{!remarks.trim()&&<span className="text-xs text-muted-foreground">Add workflow remarks above to confirm the change.</span>}</div></div>}{capabilities.review&&!["draft","cancelled"].includes(exam.status)&&<div className="border-t pt-4 space-y-3"><p className="text-sm">Reopening withdraws this revision and dependent annual reports. Fresh approval and release are required.</p><label className="flex gap-2 items-center text-sm"><input type="checkbox" disabled={disabled} checked={reopenDraft} onChange={e=>setReopenDraft(e.target.checked)}/>Reopen configuration and roster</label>{!reopenDraft&&exam.category!=="annual"&&<AcademicField label="Paper to reopen"><select className={academicInput} disabled={disabled} value={reopenPaper} onChange={e=>setReopenPaper(e.target.value)}><option value="">All papers</option>{workspace.papers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></AcademicField>}<Button variant="outline" disabled={disabled||!remarks.trim()} onClick={()=>onAction("reopen",{remarks,draft:reopenDraft,...(!reopenDraft&&reopenPaper?{paper_id:reopenPaper}:{})})}>Reopen for correction</Button></div>}</AcademicPanel>
    {exam.status==="draft"&&<DraftConfiguration workspace={workspace} configuration={configuration} disabled={disabled} onAction={onAction}/>}
    {workspace.sources.length>0&&<AcademicPanel title="Annual source assessments">{workspace.sources.map(s=><p className="text-sm" key={s.source_exam_id}>{s.name} · {CBSE_CATEGORY_LABELS[s.category]} {s.sequence} · {s.weight}%</p>)}</AcademicPanel>}
    {exam.category!=="annual"&&exam.status!=="draft"&&workspace.papers.map(p=><PaperEntry key={p.id} paper={p} workspace={workspace} disabled={disabled} onAction={onAction}/>)}
    {exam.status!=="draft"&&<StudentReview workspace={workspace} disabled={disabled} onAction={onAction}/>}
    <ReportsReview workspace={workspace} disabled={disabled} onAction={onAction}/>
    <AcademicPanel title="Audit history"><div className="max-h-96 overflow-auto space-y-2">{workspace.audit.map(event=><div className="border-b pb-2 text-sm" key={event.id}><p>{event.action.replace(/_/g," ")} · {new Date(event.created_at).toLocaleString()}</p>{event.remarks&&<p>{event.remarks}</p>}<p className="text-xs text-muted-foreground">Actor {event.actor_id}</p></div>)}{!workspace.audit.length&&<p className="text-sm text-muted-foreground">No changes recorded yet.</p>}</div></AcademicPanel>
  </div>;
}
