-- Archived, deleted, or login-disabled students must not appear in staff
-- approval queues (offer waivers, offer letters, concessions, AN bypass, etc.).

CREATE OR REPLACE FUNCTION public.lead_hidden_from_staff_queues(_lead_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
AS $fn$
  SELECT EXISTS (
    SELECT 1
      FROM public.students s
     WHERE s.lead_id = _lead_id
       AND (
         COALESCE(s.login_disabled, false)
         OR s.archived_at IS NOT NULL
         OR s.deleted_at IS NOT NULL
       )
  );
$fn$;

CREATE OR REPLACE FUNCTION public.student_hidden_from_staff_queues(_student_id uuid)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path TO 'public'
AS $fn$
  SELECT EXISTS (
    SELECT 1
      FROM public.students s
     WHERE s.id = _student_id
       AND (
         COALESCE(s.login_disabled, false)
         OR s.archived_at IS NOT NULL
         OR s.deleted_at IS NOT NULL
       )
  );
$fn$;

GRANT EXECUTE ON FUNCTION public.lead_hidden_from_staff_queues(uuid) TO authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.student_hidden_from_staff_queues(uuid) TO authenticated, service_role;

CREATE OR REPLACE FUNCTION public.admission_bypass_generate_an(_lead_id uuid, _reason text)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
DECLARE
  v_lead     public.leads%ROWTYPE;
  v_status   jsonb;
  v_an       text;
  v_snapshot jsonb;
  v_actor    text;
BEGIN
  IF NOT public.has_role(auth.uid(), 'super_admin'::public.app_role) THEN
    RAISE EXCEPTION 'Forbidden: super_admin only';
  END IF;
  IF COALESCE(TRIM(_reason), '') = '' THEN
    RAISE EXCEPTION 'Reason required to bypass the document check';
  END IF;

  SELECT * INTO v_lead FROM public.leads WHERE id = _lead_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Lead not found'; END IF;
  IF public.lead_hidden_from_staff_queues(_lead_id) THEN
    RAISE EXCEPTION 'Cannot generate AN: student is archived, deleted, or login-disabled';
  END IF;
  IF v_lead.pre_admission_no IS NULL THEN
    RAISE EXCEPTION 'Cannot generate AN: student is not pre-admitted (no PAN)';
  END IF;
  IF v_lead.admission_no IS NOT NULL THEN
    RETURN v_lead.admission_no;
  END IF;

  v_status := public.lead_fee_status(_lead_id);
  IF NOT (v_status->>'twenty_five_complete')::boolean THEN
    RAISE EXCEPTION 'Cannot generate AN: 25%% of year-1 fee is not yet paid';
  END IF;

  SELECT a.admission_doc_status INTO v_snapshot
    FROM public.applications a WHERE a.lead_id = _lead_id
   ORDER BY a.created_at DESC NULLS LAST LIMIT 1;

  v_an := public.fn_issue_admission_no(_lead_id);

  SELECT COALESCE(p.display_name, p.email, auth.uid()::text) INTO v_actor
    FROM public.profiles p WHERE p.id = auth.uid();

  INSERT INTO public.admission_bypass_audit (lead_id, admission_no, actor_id, actor_name, reason, doc_snapshot)
  VALUES (_lead_id, v_an, auth.uid(), v_actor, _reason, COALESCE(v_snapshot, '{}'::jsonb));

  INSERT INTO public.lead_activities (lead_id, type, description)
  VALUES (_lead_id, 'system',
          'Admission number ' || COALESCE(v_an, '(unknown)') ||
          ' generated by super_admin override (document check bypassed): ' || _reason);

  RETURN v_an;
END;
$function$;

CREATE OR REPLACE FUNCTION public.decide_fee_concession(
  _id      uuid,
  _approve boolean,
  _note    text DEFAULT NULL
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_profile uuid;
  v_student uuid;
BEGIN
  IF NOT public.has_role(auth.uid(), 'super_admin') THEN
    RAISE EXCEPTION 'Only a super admin can decide a concession';
  END IF;

  SELECT student_id INTO v_student FROM public.concessions WHERE id = _id;
  IF v_student IS NULL THEN
    RAISE EXCEPTION 'Concession not found';
  END IF;
  IF public.student_hidden_from_staff_queues(v_student) THEN
    RAISE EXCEPTION 'Cannot decide concession: student is archived, deleted, or login-disabled';
  END IF;

  SELECT id INTO v_profile FROM public.profiles WHERE user_id = auth.uid();

  UPDATE public.concessions
     SET status                  = CASE WHEN _approve THEN 'approved' ELSE 'rejected' END,
         approved_by             = CASE WHEN _approve THEN v_profile ELSE approved_by END,
         approved_by_principal   = COALESCE(approved_by_principal, auth.uid()),
         principal_decision_at   = COALESCE(principal_decision_at, now()),
         approved_by_super_admin = auth.uid(),
         super_admin_decision_at = now(),
         decision_note           = NULLIF(btrim(COALESCE(_note, '')), '')
   WHERE id = _id;

  PERFORM public.sync_fee_ledger_concessions(v_student);
END;
$$;

CREATE OR REPLACE VIEW public.pending_approvals AS
 SELECT 'concession'::text AS kind, (c.id)::text AS id, c.status,
    (c.student_id)::text AS subject_id, s.name AS subject_name,
    c.type AS detail_type, c.value AS detail_value, c.reason,
    (c.requested_by)::text AS requested_by_id, c.created_at,
    CASE WHEN (c.status = 'pending_principal'::text) THEN 'principal'::text
         WHEN (c.status = 'pending_super_admin'::text) THEN 'super_admin'::text
         ELSE NULL::text END AS pending_role
   FROM (concessions c LEFT JOIN students s ON ((s.id = c.student_id)))
  WHERE (c.status = ANY (ARRAY['pending_principal'::text, 'pending_super_admin'::text]))
    AND NOT public.student_hidden_from_staff_queues(c.student_id)
UNION ALL
 SELECT 'offer_letter'::text, (ol.id)::text, ol.approval_status, (ol.lead_id)::text, l.name,
    'flat'::text, ol.net_fee, NULL::text, (ol.issued_by)::text, ol.created_at, 'principal'::text
   FROM (offer_letters ol LEFT JOIN leads l ON ((l.id = ol.lead_id)))
  WHERE (ol.approval_status = 'pending_principal'::text)
    AND NOT public.lead_hidden_from_staff_queues(ol.lead_id)
UNION ALL
 SELECT 'offer_edit'::text, (er.id)::text, er.status, (ol.lead_id)::text, l.name,
    'edit_request'::text, NULL::numeric, er.reason, (er.requested_by)::text, er.created_at, 'super_admin'::text
   FROM ((offer_letter_edit_requests er
     JOIN offer_letters ol ON ((ol.id = er.offer_letter_id)))
     LEFT JOIN leads l ON ((l.id = ol.lead_id)))
  WHERE (er.status = 'pending'::text)
    AND NOT public.lead_hidden_from_staff_queues(ol.lead_id)
UNION ALL
 SELECT 'student_contact_change'::text, (scr.id)::text, scr.status, (scr.student_id)::text, s.name,
    scr.field_name, NULL::numeric, scr.reason, (scr.requested_by)::text, scr.created_at, 'principal'::text
   FROM (student_contact_change_requests scr LEFT JOIN students s ON ((s.id = scr.student_id)))
  WHERE (scr.status = 'pending'::text)
    AND NOT public.student_hidden_from_staff_queues(scr.student_id)
UNION ALL
 SELECT 'lead_deletion'::text, (ldr.id)::text, 'pending_admin'::text, (ldr.lead_id)::text, l.name,
    ldr.reason, NULL::numeric, ldr.custom_message, (ldr.requested_by)::text, ldr.created_at, 'super_admin'::text
   FROM (lead_deletion_requests ldr LEFT JOIN leads l ON ((l.id = ldr.lead_id)))
  WHERE (ldr.status = 'pending'::text)
UNION ALL
 SELECT 'pending_an'::text, (l.id)::text, 'pending'::text, (s.id)::text, s.name,
    'pending_an'::text, NULL::numeric, NULL::text, NULL::text, s.updated_at, 'principal'::text
   FROM (students s JOIN leads l ON ((l.id = s.lead_id)))
  WHERE s.pre_admission_no IS NOT NULL
    AND s.admission_no IS NULL
    AND NOT public.lead_hidden_from_staff_queues(l.id)
    AND NOT public.lead_docs_ready_for_admission(l.id)
    AND (public.lead_fee_status(l.id)->>'twenty_five_complete')::boolean;
