-- Super-admin override: issue the admission number despite the document gate.
--
-- The mandatory-docs gate can hold a legitimately-paid student when a document
-- was wrongly flagged or is genuinely pending. A super_admin may bypass the
-- DOCUMENT gate (never the fee gate) and generate the AN. Every bypass is
-- recorded append-only in admission_bypass_audit with the actor, reason, and a
-- snapshot of the document status at override time.

CREATE TABLE IF NOT EXISTS public.admission_bypass_audit (
  id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  lead_id      uuid NOT NULL REFERENCES public.leads(id) ON DELETE CASCADE,
  admission_no text,
  actor_id     uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  actor_name   text,
  reason       text NOT NULL,
  doc_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at   timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.admission_bypass_audit ENABLE ROW LEVEL SECURITY;

-- Append-only: read for oversight roles, written solely by the DEFINER RPC.
DROP POLICY IF EXISTS admission_bypass_audit_read ON public.admission_bypass_audit;
CREATE POLICY admission_bypass_audit_read ON public.admission_bypass_audit
  FOR SELECT TO authenticated
  USING (public.has_role(auth.uid(), 'super_admin'::public.app_role)
         OR public.has_role(auth.uid(), 'principal'::public.app_role));

GRANT SELECT ON public.admission_bypass_audit TO authenticated;

-- ── The override RPC ─────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.admission_bypass_generate_an(_lead_id uuid, _reason text)
 RETURNS text
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_lead     public.leads%ROWTYPE;
  v_status   jsonb;
  v_an       text;
  v_snapshot jsonb;
  v_actor    text;
BEGIN
  IF NOT public.has_role(auth.uid(), 'super_admin'::public.app_role) THEN
    RAISE EXCEPTION 'Forbidden: super_admin only';
  END IF;
  IF COALESCE(TRIM(_reason), '') = '' THEN
    RAISE EXCEPTION 'Reason required to bypass the document check';
  END IF;

  SELECT * INTO v_lead FROM public.leads WHERE id = _lead_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Lead not found'; END IF;
  IF v_lead.pre_admission_no IS NULL THEN
    RAISE EXCEPTION 'Cannot generate AN: student is not pre-admitted (no PAN)';
  END IF;
  IF v_lead.admission_no IS NOT NULL THEN
    RETURN v_lead.admission_no;  -- already admitted, no-op
  END IF;

  -- The FEE gate is never bypassed.
  v_status := public.lead_fee_status(_lead_id);
  IF NOT (v_status->>'twenty_five_complete')::boolean THEN
    RAISE EXCEPTION 'Cannot generate AN: 25%% of year-1 fee is not yet paid';
  END IF;

  -- Snapshot the document status for the audit trail before issuing.
  SELECT a.admission_doc_status INTO v_snapshot
    FROM public.applications a WHERE a.lead_id = _lead_id
   ORDER BY a.created_at DESC NULLS LAST LIMIT 1;

  v_an := public.fn_issue_admission_no(_lead_id);

  SELECT COALESCE(p.display_name, p.email, auth.uid()::text) INTO v_actor
    FROM public.profiles p WHERE p.id = auth.uid();

  INSERT INTO public.admission_bypass_audit (lead_id, admission_no, actor_id, actor_name, reason, doc_snapshot)
  VALUES (_lead_id, v_an, auth.uid(), v_actor, _reason, COALESCE(v_snapshot, '{}'::jsonb));

  INSERT INTO public.lead_activities (lead_id, type, description)
  VALUES (_lead_id, 'system',
          'Admission number ' || COALESCE(v_an, '(unknown)') ||
          ' generated by super_admin override (document check bypassed): ' || _reason);

  RETURN v_an;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.admission_bypass_generate_an(uuid, text) TO authenticated;
