-- Keep pg_stat_statements useful for daily performance review.
-- Every night at 2:00 AM IST (20:30 UTC), archive the current top expensive
-- statements and reset counters so the next report reflects fresh workload.

CREATE TABLE IF NOT EXISTS public.query_performance_snapshots (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  captured_at timestamptz NOT NULL DEFAULT now(),
  stats_reset_at timestamptz,
  queryid bigint,
  calls bigint NOT NULL,
  total_exec_time_ms numeric NOT NULL,
  mean_exec_time_ms numeric NOT NULL,
  pct_of_total_exec_time numeric NOT NULL,
  rows bigint NOT NULL,
  sample_query text NOT NULL
);

ALTER TABLE public.query_performance_snapshots ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_query_performance_snapshots_captured_at
  ON public.query_performance_snapshots (captured_at DESC);

CREATE OR REPLACE FUNCTION public.snapshot_and_reset_pg_stat_statements(
  p_limit integer DEFAULT 20
)
RETURNS integer
LANGUAGE plpgsql
SET search_path = public, extensions
AS $$
DECLARE
  v_captured_at timestamptz := now();
  v_stats_reset_at timestamptz;
  v_rows integer := 0;
BEGIN
  SELECT info.stats_reset INTO v_stats_reset_at
  FROM extensions.pg_stat_statements_info info;

  WITH ranked AS (
    SELECT
      s.queryid,
      s.calls,
      round(s.total_exec_time::numeric, 2) AS total_exec_time_ms,
      round(s.mean_exec_time::numeric, 2) AS mean_exec_time_ms,
      round((100 * s.total_exec_time / nullif(sum(s.total_exec_time) OVER (), 0))::numeric, 2) AS pct_of_total_exec_time,
      s.rows,
      left(s.query, 500) AS sample_query
    FROM extensions.pg_stat_statements s
    WHERE s.dbid = (
      SELECT d.oid
      FROM pg_database d
      WHERE d.datname = current_database()
    )
    ORDER BY s.total_exec_time DESC
    LIMIT LEAST(GREATEST(COALESCE(p_limit, 20), 1), 100)
  ),
  inserted AS (
    INSERT INTO public.query_performance_snapshots (
      captured_at,
      stats_reset_at,
      queryid,
      calls,
      total_exec_time_ms,
      mean_exec_time_ms,
      pct_of_total_exec_time,
      rows,
      sample_query
    )
    SELECT
      v_captured_at,
      v_stats_reset_at,
      queryid,
      calls,
      total_exec_time_ms,
      mean_exec_time_ms,
      pct_of_total_exec_time,
      rows,
      sample_query
    FROM ranked
    RETURNING 1
  )
  SELECT count(*)::integer INTO v_rows
  FROM inserted;

  PERFORM extensions.pg_stat_statements_reset(0::oid, 0::oid, 0::bigint, false);

  RETURN v_rows;
END;
$$;

REVOKE ALL ON FUNCTION public.snapshot_and_reset_pg_stat_statements(integer) FROM PUBLIC;

-- 2:00 AM IST = 20:30 UTC.
SELECT cron.unschedule('snapshot-reset-pg-stat-statements')
WHERE EXISTS (
  SELECT 1
  FROM cron.job
  WHERE jobname = 'snapshot-reset-pg-stat-statements'
);

SELECT cron.schedule(
  'snapshot-reset-pg-stat-statements',
  '30 20 * * *',
  $$SELECT public.snapshot_and_reset_pg_stat_statements(20)$$
);
