-- Fix scoring system: clear bad data, rebalance, add penalty weight

-- 1. Clear all score events (they were generated by bulk migrations, not real actions)
TRUNCATE public.counsellor_score_events;
TRUNCATE public.score_penalty_log;

-- 2. Replace the trigger function with a smarter version
-- Key changes:
--   - Calls are the PRIMARY scoring mechanism (higher points)
--   - First contact within same day = bonus
--   - Stage changes only score for meaningful transitions (not system updates)
--   - Ignore updates where only non-stage fields changed
--   - Heavier penalties for overdue followups and uncontacted new leads

CREATE OR REPLACE FUNCTION public.fn_record_counsellor_score()
RETURNS trigger AS $$
DECLARE
  v_counsellor_id uuid;
  v_lead_id uuid;
  v_points integer;
BEGIN
  -- === CALL LOGS (INSERT) — Primary scoring mechanism ===
  IF TG_TABLE_NAME = 'call_logs' AND TG_OP = 'INSERT' THEN
    SELECT l.counsellor_id INTO v_counsellor_id
    FROM public.leads l WHERE l.id = NEW.lead_id;
    v_lead_id := NEW.lead_id;

    IF v_counsellor_id IS NULL THEN RETURN NEW; END IF;

    -- First contact bonus (lead has never been called before)
    IF NOT EXISTS (
      SELECT 1 FROM public.call_logs WHERE lead_id = NEW.lead_id AND id != NEW.id
    ) THEN
      -- Extra bonus if first contact is same day as lead creation
      IF EXISTS (
        SELECT 1 FROM public.leads
        WHERE id = NEW.lead_id
          AND created_at::date = now()::date
      ) THEN
        INSERT INTO public.counsellor_score_events (counsellor_id, lead_id, action_type, points, metadata)
        VALUES (v_counsellor_id, v_lead_id, 'first_contact_same_day', 15,
          jsonb_build_object('disposition', NEW.disposition));
      ELSE
        INSERT INTO public.counsellor_score_events (counsellor_id, lead_id, action_type, points, metadata)
        VALUES (v_counsellor_id, v_lead_id, 'first_contact', 8,
          jsonb_build_object('disposition', NEW.disposition));
      END IF;
    END IF;

    -- Disposition-based scoring (every call gets scored)
    v_points := CASE NEW.disposition
      WHEN 'interested' THEN 10
      WHEN 'call_back' THEN 5
      WHEN 'not_answered' THEN 2
      WHEN 'busy' THEN 2
      WHEN 'voicemail' THEN 2
      WHEN 'not_interested' THEN 0  -- neutral, not counsellor's fault
      WHEN 'do_not_contact' THEN 0
      WHEN 'wrong_number' THEN 0
      WHEN 'ineligible' THEN 0
      ELSE 1  -- any call is work
    END;

    IF v_points > 0 THEN
      INSERT INTO public.counsellor_score_events (counsellor_id, lead_id, action_type, points, metadata)
      VALUES (v_counsellor_id, v_lead_id, 'call_made', v_points,
        jsonb_build_object('disposition', NEW.disposition, 'duration', COALESCE(NEW.duration_seconds, 0)));
    END IF;

    -- Bonus for long calls (actually had a conversation)
    IF COALESCE(NEW.duration_seconds, 0) >= 120 THEN
      INSERT INTO public.counsellor_score_events (counsellor_id, lead_id, action_type, points, metadata)
      VALUES (v_counsellor_id, v_lead_id, 'quality_call', 5,
        jsonb_build_object('duration', NEW.duration_seconds));
    END IF;

    RETURN NEW;

  -- === LEADS (UPDATE) — Only score meaningful stage transitions ===
  ELSIF TG_TABLE_NAME = 'leads' AND TG_OP = 'UPDATE' THEN
    v_counsellor_id := NEW.counsellor_id;
    v_lead_id := NEW.id;

    IF v_counsellor_id IS NULL THEN RETURN NEW; END IF;

    -- Only score if stage actually changed
    IF OLD.stage IS DISTINCT FROM NEW.stage THEN
      -- Only score high-value stage transitions (not intermediate system stages)
      v_points := CASE NEW.stage::text
        WHEN 'visit_scheduled' THEN 5
        WHEN 'offer_sent' THEN 15
        WHEN 'token_paid' THEN 25
        WHEN 'admitted' THEN 50
        ELSE 0
      END;

      IF v_points > 0 THEN
        INSERT INTO public.counsellor_score_events (counsellor_id, lead_id, action_type, points, metadata)
        VALUES (v_counsellor_id, v_lead_id, 'stage_advance', v_points,
          jsonb_build_object('from_stage', OLD.stage::text, 'to_stage', NEW.stage::text));
      END IF;
    END IF;

    RETURN NEW;

  -- === CAMPUS VISITS (INSERT/UPDATE) ===
  ELSIF TG_TABLE_NAME = 'campus_visits' THEN
    SELECT l.counsellor_id INTO v_counsellor_id FROM public.leads l WHERE l.id = NEW.lead_id;
    v_lead_id := NEW.lead_id;

    IF v_counsellor_id IS NULL THEN RETURN NEW; END IF;

    IF TG_OP = 'INSERT' THEN
      IF COALESCE(NEW.visit_type, 'scheduled') = 'walk_in' THEN
        INSERT INTO public.counsellor_score_events (counsellor_id, lead_id, action_type, points, metadata)
        VALUES (v_counsellor_id, v_lead_id, 'walk_in_recorded', 20, '{}');
      ELSE
        INSERT INTO public.counsellor_score_events (counsellor_id, lead_id, action_type, points, metadata)
        VALUES (v_counsellor_id, v_lead_id, 'visit_scheduled', 8, '{}');
      END IF;

    ELSIF TG_OP = 'UPDATE' THEN
      IF OLD.status != 'completed' AND NEW.status = 'completed' AND COALESCE(NEW.visit_type, 'scheduled') != 'walk_in' THEN
        INSERT INTO public.counsellor_score_events (counsellor_id, lead_id, action_type, points, metadata)
        VALUES (v_counsellor_id, v_lead_id, 'visit_completed', 15, '{}');
      END IF;
      IF OLD.status != 'no_show' AND NEW.status = 'no_show' THEN
        INSERT INTO public.counsellor_score_events (counsellor_id, lead_id, action_type, points, metadata)
        VALUES (v_counsellor_id, v_lead_id, 'visit_no_show', -5, '{}');
      END IF;
    END IF;

    RETURN NEW;

  -- === LEAD FOLLOWUPS (UPDATE) — Score completions ===
  ELSIF TG_TABLE_NAME = 'lead_followups' AND TG_OP = 'UPDATE' THEN
    SELECT l.counsellor_id INTO v_counsellor_id FROM public.leads l WHERE l.id = NEW.lead_id;
    v_lead_id := NEW.lead_id;

    IF v_counsellor_id IS NULL THEN RETURN NEW; END IF;

    IF OLD.status != 'completed' AND NEW.status = 'completed' THEN
      -- Bonus for completing on time
      IF NEW.completed_at <= NEW.scheduled_at + interval '24 hours' THEN
        INSERT INTO public.counsellor_score_events (counsellor_id, lead_id, action_type, points, metadata)
        VALUES (v_counsellor_id, v_lead_id, 'followup_on_time', 5, '{}');
      ELSE
        INSERT INTO public.counsellor_score_events (counsellor_id, lead_id, action_type, points, metadata)
        VALUES (v_counsellor_id, v_lead_id, 'followup_late', 2, '{}');
      END IF;
    END IF;

    RETURN NEW;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
